### ISSUE TITLE
[Bug] Laravel Integration with Vue Material Dashboard PRO

### ISSUE THREAD

**Issue by Tareque2208** [creativetimofficial/ct-vue-material-dashboard-pro#101]
### Version
1.3.2
### Reproduction link
https://gitlab.com/alpha-health/alpha-admin-test
### Operating System
Windows
### Device
Desktop
### Browser & Version
Google Chrome. Version 79.0.3945.88
### Steps to reproduce
1. You can go with the steps from readme.md
### What is expected?
As I have installed the packages of UI kit and placed the src folder as well. It suppose to work well with the router only. I mean when I can give the specific router from the UI design I suppose to show the pages with components.
### What is actually happening?
@components  or @pages is not found but in the beginning I used ~ instead of @ in mix.webpackConfig. So,I replaced @ with ~ and it is showing error.

---
### Solution
1. Is the ~ working well after replacing @ ?
2. Though I replaced all @ with ~ for redirecting. I again seeing the error conducting with @. How is this happening?
3. packages installation and other files like browserlistrc,babel.config.js can't be the reason for errors right?

**Comment by dragosct10** [comment]
Hi, @Tareque2208! Thank you for using our products. I already answered you on the email and I gave you a tutorial link. It's difficult to help you with what you want because we don't have any product with vuejs and laravel integrated. 

Regards,
Dragos

**Comment by Tareque2208** [comment]
Hi, Thanks for your concern but All I wanted to know Is It possible and
done integrating your template with laravel? If, yes please give me some
suggestions or Help me out with some errors I am facing right now.
Otherwise buying your product would be totally waste of money for me.


Ahmed Tareque
Computer Science & Engineering
BRAC University
Dhaka,Bangladesh.
Contact Number : +8801703652563 , +8801534747141

-------------------------------------------------------------------------------------------------------------------------------------

"My prayers, my sacrifices, my life and my death are all for Allah, the
Lord of the worlds." - Quran (6:162)
"Spread Love everywhere you go. Let no one ever come to you without leaving
happier !" - Mother Teresa.
"Never Give Up, That's not the solution !"

**Comment by dragosct10** [comment]
Hi! Yes, the product can be integrated with laravel. See this tutorial https://www.youtube.com/watch?v=DJ6PD_jBtU0 it can help you. Like I told you we don't integrate until now a vue product with laravel so it's difficult to help you with something that we don't experience yet. We will have vue products with laravel integrated in the near future! 

Thank you for your understanding!  

Regards,
Dragos
