### ISSUE TITLE
[Bug] Chartist responsive options not passed to chart init function

### ISSUE THREAD

**Issue by thaddeus** [creativetimofficial/ct-vue-material-dashboard-pro#103]
### Version
1.3.2
### Reproduction link
https://demos.creative-tim.com/vue-material-dashboard-pro/#/dashboard
### Operating System
Any
### Device
Any
### Browser & Version
Any
### Steps to reproduce
1. Create a chart-card and add responsive options as an attribute.
2. Responsive options will not apply to the Chartist chart
### What is expected?
initChart(Chartist) {
      var chartIdQuery = `#${this.chartId}`;
      Chartist[this.chartType](chartIdQuery, this.chartData, this.chartOptions, this.chartResponsiveOptions, this.chartAnimation);
    },
### What is actually happening?
initChart(Chartist) {
      var chartIdQuery = `#${this.chartId}`;
      Chartist[this.chartType](chartIdQuery, this.chartData, this.chartOptions, this.chartAnimation);
    },

---
### Solution
Add "this.chartResponsiveOptions," to Chartist init

**Comment by dragosct10** [comment]
Hi, @thaddeus! Thank you for using our products and sorry for the late response. We will analyze the code and if it's all good we will implement this in the next update. 

Regards,
Dragos
