### ISSUE TITLE
There is a bug about Memory leak on your offical demo

### ISSUE THREAD

**Issue by jnzwt** [creativetimofficial/ct-vue-material-dashboard-pro#104]
After our company bought your vue-material-dashboard-pro

I found there is a serious memory leak problem in the multi selection. When you expand and merge the multi selection (especially when there are dozens or hundreds of options), you can see that the memory occupied by the browser increases infinitely, and you can see similar situation when you switch the routes containing the multi selection components.

in this page you also can verify it
https://demos.creative-tim.com/vue-material-dashboard-pro/#/forms/extended
nearly "Godfather" you can try(open and close the multi-selection), and open F12 memory panel see.

i tryed to solved, but failed. maybe a method named "getselect()" have problem...just maybe...

can you fix it, and let me known? thanks very much.

**Comment by dragosct10** [comment]
Hi, @jnzwt! Thank you for using our products and sorry for the late response. The product is built on vuematerial framework and the components are from the vuematerial itself so the fix of the issue depends only on the vuematerial. We hope that they will make an update soon. 

Regards,
Dragos

**Comment by jnzwt** [comment]
……ok.
