### ISSUE TITLE
 open page with "sidebar" MAXIMIZED

### ISSUE THREAD

**Issue by intelmib** [creativetimofficial/ct-vue-material-dashboard-pro#105]
to open the "sidebar" already MAXIMIZED

changed index.html
'body class = "sidebar-mini"
per
'body'

The problem is when I open on the MOBILE:
it already loads open, capping the screen

how do I open it hidden only on the cell phone?
or
how do i open open only on the desktop?

**Comment by dragosct10** [comment]
Hi, @intelmib! Thank you for using our products. You can remove the class sidebar-mini from the body tag and after you can go on src/pages/Dashboard/Layout/DashboardLayout.vue and on the div with class `.wrapper` you can add the highlighted row code: 
<img width="453" alt="Screenshot 2020-03-25 at 10 31 13" src="https://user-images.githubusercontent.com/17456857/77516905-db76f980-6e83-11ea-8ae0-e810a55b9935.png">

Then you just have to add in the data the following prop: 

<img width="631" alt="Screenshot 2020-03-25 at 10 32 39" src="https://user-images.githubusercontent.com/17456857/77517064-2133c200-6e84-11ea-872e-76d11104c525.png">

Regards,
Dragos

**Comment by intelmib** [comment]
It worked perfect

Thank you excellent work
