### ISSUE TITLE
The tabs component is not responsive

### ISSUE THREAD

**Issue by LuanFreitas** [creativetimofficial/ct-vue-material-dashboard-pro#11]
The tabs component is not responsive in mobile mode, is it normal?

**Comment by dragosct10** [comment]
Hi, @LuanFreitas! Please send us an image to see where is the problem. 

Regards, 
Dragos

**Comment by LuanFreitas** [comment]
### Desktop

<img width="1146" alt="screen shot 2018-08-31 at 11 23 36" src="https://user-images.githubusercontent.com/5608139/44918096-85c28580-ad10-11e8-8972-8343c77b7218.png">

### Mobile

<img width="373" alt="screen shot 2018-08-31 at 11 24 04" src="https://user-images.githubusercontent.com/5608139/44918114-907d1a80-ad10-11e8-92e0-fa08f32e30a0.png">

**Comment by dragosct10** [comment]
Hi! Please add on the class `.md-tabs-navigation` this property : `overflow:scroll`. 
Regards, 
Dragos

**Comment by murilolopes** [comment]
@LuanFreitas , ta gostando desse produto? To pensando muito em comprar

**Comment by LuanFreitas** [comment]
This property already exists and was automatically set by the tag: `<nav-tabs-card>.` I tried to force the `overflow: scroll` property but without success.

<img width="1133" alt="screen shot 2018-08-31 at 11 49 37" src="https://user-images.githubusercontent.com/5608139/44919460-f919c680-ad13-11e8-91f1-27402c03f8a2.png">

**Comment by LuanFreitas** [comment]
@murilolopes, cara aqui na empresa nós curtimos bastante. Já temos um mockup quase completo com várias telas utilizando o produto, aparece um bug ou outro que acredito ser normal. O suporte aqui no github pra isso tem sido muito bom.

**Comment by murilolopes** [comment]
Show @LuanFreitas eu estou muito interessado mesmo em comprar tanto para projetos pessoais, quando apresentar isso aqui na empresa que trabalho, pois em breve nosso produto será redesenhado e acho que isso pode ser uma base. Eu gostaria de saber também se vocês compraram apenas para mockar as telas ou pretendem fazer o projeto do produto em sim com o vue? Se sim tem estrutura própria de projeto ou vai usar a mesma do dashboard pro.  Eu achei ela legal, só não sei ainda se da usar ela como base pra tudo.

**Comment by LuanFreitas** [comment]
@murilolopes estamos com um mockup atualmente, mas é a base do projeto. Você tem que usar a estrutura que eles disponibilizam pra poder funcionar corretamente. É Vue, porém notei algumas pastas que eu não tinha costume de ver nesse tipo de projeto. Mas é bacana, da pra usar pra tudo, com certeza.
