### ISSUE TITLE
[Bug] Vue component <md-select> give error undefined

### ISSUE THREAD

**Issue by code-newbie** [creativetimofficial/ct-vue-material-dashboard-pro#113]
### Version
Version 1.4.0
### Reproduction link
https://codepen.io/code-newbie/pen/qBNEzaZ
### Operating System
macOS Catalina v10.15.7
### Device
MacBook Pro (15', 2017)
### Browser & Version
Google Chrome Version 86.0.4240.75
### Steps to reproduce
1. Download fresh source code from >> https://www.creative-tim.com/bundle-product/download/vue-material-dashboard-pro/58423d5d9af3de1b82ff
2. Install dependencies & run same as README.md
3. Open this url after the app running >> http://localhost:8080/#/forms/extended
4. Open developer tools and inspect on console, then will displayed error.
### What is expected?
No error for component <md-select> for single selection.
### What is actually happening?
Component <md-select> displayed error for single selection.

---

**Comment by code-newbie** [comment]
<img width="952" alt="Screen Shot 2020-10-10 at 14 38 16" src="https://user-images.githubusercontent.com/1773554/95657040-7f807380-0b3c-11eb-838a-04e5157707b8.png">

**Comment by code-newbie** [comment]
<img width="1232" alt="Screen Shot 2020-10-10 at 14 38 28" src="https://user-images.githubusercontent.com/1773554/95657047-94f59d80-0b3c-11eb-9ffa-049e5d03f2c7.png">

**Comment by code-newbie** [comment]
Hi @dragosct10 , thanks for the update. Seem it related to this issue >> https://github.com/vuematerial/vue-material/pull/2262 

I try to downgrade to lower version as suggest in here >> https://github.com/vuematerial/vue-material/issues/2270
But seem not work. Any idea how to fix ?


regards,
A.Rachmat

**Comment by christhofer** [comment]
@code-newbie I use v1.0.0-beta-14, no error for me.

**Comment by leonardoks16** [comment]
It worked when I changed to v1.0.0-beta-14. Thank you

**Comment by LuisFerMM** [comment]
Same problem, @christhofer or @leonardoks16 that version is for the template or what exactly? If its the template version, how I update it?
Regards

**Comment by christhofer** [comment]
@LuisFerMM it's vue-material version. 

Run this command:
`npm install vue-material@1.0.0-beta-14`

**Comment by leonardoks16** [comment]
I gave away and changed my UI Material, but @christhofer solution should work for you.

**Comment by hdzjulio** [comment]
I do not think of your help, since when you update to 1.5.1 no longer correctly shows me md-select, you are using version 1.4.0 updates as I need to implement on CI/CD
![image](https://user-images.githubusercontent.com/4045112/189805938-4671cafe-07a1-4525-a8c1-dea75d9db60f.png)
