### ISSUE TITLE
Bug setting date in datepicker

### ISSUE THREAD

**Issue by LuanFreitas** [creativetimofficial/ct-vue-material-dashboard-pro#13]
# Expected Behavior
Select a date

# Current Behavior
Entire screen freeze after selecting a date

# Failure Information (for bugs)
Entire screen freeze after selecting a date

## Steps to Reproduce
See video recording available at [this link](https://cdn.mobradio.com.br/datepicker-error.mov)

## Context
* Operating System: Mac OS 10.13.6
* Browser and Version: Chrome 69.0.3497.81

**Comment by dragosct10** [comment]
Hi, @LuanFreitas! Thank you for this video. Please tell us if you made some changes in your project, or if you updated your package.json file because like you will see on our live demo everything is working fine with datepicker and whats it's happening in your project it's very weird? 

Regards, 
Dragos

**Comment by LuanFreitas** [comment]
Some dependencies...

**dependencies**: {
        "chartist": "^0.11.0",
        "coreutils": "^0.3.0",
        "element-ui": "^2.4.6",
        "es6-promise": "^4.1.1",
        "fullcalendar": "^3.9.0",
        "fuse.js": "^3.2.0",
        "google-maps": "^3.2.1",
        "i": "^0.3.6",
        "jquery": "^3.2.1",
        "jvectormap-next": "^3.0.0",
        "nouislider": "^10.0.0",
        "npm": "^6.3.0",
        "perfect-scrollbar": "^1.3.0",
        "sweetalert2": "^7.20.7",
        "tween.js": "^16.6.0",
        "vee-validate": "^2.0.9",
        "vue": "^2.5.16",
        "vue-chartjs": "^3.1.0",
        "vue-clickaway": "^2.1.0",
        "vue-i18n": "^8.0.0",
        "vue-loader": "^15.4.0",
        "vue-material": "^1.0.0-beta-10.2",
        "vue-router": "^3.0.1",
        "vue2-google-maps": "^0.8.4",
        "vue2-transitions": "^0.2.2",
        "vuejs-datepicker": "^0.9.29"
    }

**Comment by LuanFreitas** [comment]
I noticed that 10 events are set off after choosing a date.
But sometimes the screen freezes and only 4 events are called.

# Success:
<img width="904" alt="screen shot 2018-09-06 at 15 45 35" src="https://user-images.githubusercontent.com/5608139/45178911-700bff00-b1ed-11e8-9150-bd77e1a29f29.png">

# Failed:
<img width="925" alt="screen shot 2018-09-06 at 15 46 20" src="https://user-images.githubusercontent.com/5608139/45178988-a0539d80-b1ed-11e8-83d1-f7e70a3e383d.png">

**Comment by dragosct10** [comment]
Hi, @LuanFreitas! I forgot to ask you if you use the latest version of the product which is `1.0.1` because in the latest version every plugin is updated to the latest and I see you have `"vue": "^2.5.16"` and the inspect element of your browser is saying Ready. Detected Vue 2.5.17. 

Regards,
Dragos

**Comment by LuanFreitas** [comment]
In fact, the dependencies of my project were outdated. Now I have corrected everything, but it did not solve. I do not remember a sudden change that might have caused this problem. This reminds me a lot of the "Maximum call stack size exceeded" error, however it is difficult to find because the console does not report anything.

### Update
`    "dependencies": {
        "chartist": "0.11.0",
        "coreutils": "^0.3.0",
        "element-ui": "^2.4.6",
        "es6-promise": "4.2.4",
        "fullcalendar": "3.9.0",
        "fuse.js": "3.2.1",
        "google-maps": "3.3.0",
        "i": "^0.3.6",
        "jquery": "3.3.1",
        "jvectormap-next": "3.0.0",
        "nouislider": "11.1.0",
        "npm": "6.0.1",
        "perfect-scrollbar": "1.4.0",
        "sweetalert2": "7.26.12",
        "tween.js": "^16.6.0",
        "vee-validate": "2.1.0-beta.8",
        "vue": "2.5.17",
        "vue-chartjs": "^3.1.0",
        "vue-clickaway": "2.2.2",
        "vue-i18n": "^8.0.0",
        "vue-loader": "^15.4.0",
        "vue-material": "1.0.0-beta-10.2",
        "vue-router": "3.0.1",
        "vue2-google-maps": "^0.8.4",
        "vue2-transitions": "0.2.2"
    }`

**Comment by LuanFreitas** [comment]
I found the problem. It is in the translation settings of datepicker. You showed me this solution [this](https://github.com/vuematerial/vue-material/blob/dev/src/material.js#L9) and I used it like this:

<img width="1017" alt="screen shot 2018-09-11 at 16 41 24" src="https://user-images.githubusercontent.com/5608139/45383425-9234c100-b5e1-11e8-9974-107fb049cebb.png">


When I enter a comment on the  line: **"Vue.material = init()"** , everything works again.
I set these settings in the file **"material-dashboard.js"**


Thank you!

**Comment by dragosct10** [comment]
Hi, @LuanFreitas! Oh, I'm glad that everything is working fine now. Now the vuematerial framework it's in beta version, so when it will in a stable version I'm sure that problems like this will disappear. 

Regards,
Dragos
