### ISSUE TITLE
Animated-number doesn't update

### ISSUE THREAD

**Issue by gaussianblurs** [creativetimofficial/ct-vue-material-dashboard-pro#14]
On the dashboard, there are some cards with animated numbers (`<animated-number>` tag). I tried to update the numbers via an api call, and the displayed numbers remain at their inital value.

# Expected Behavior

The number animates after being updated

# Current Behavior

The number doesn't animate and remains at the same value

## Steps to Reproduce
Use an animated number and bind it with a data model e.g: `<animated-number :value="myValue"></animated-number>`

update `myValue`

nothing happens

Browser and Version: Firefox Quantum 61.0.2 (64 bits)

**Comment by gaussianblurs** [comment]
Fixed it !
In src/components/AnimatedNumber.vue

Replace at line 47 `number(newValue, oldValue) {`
with `value(newValue, oldValue) {`

**Comment by dragosct10** [comment]
Hi, @gaussianblurs! Thank you for using our products. I'm glad that you fix it! 

Regards, 
Dragos
