### ISSUE TITLE
Syntax Error: unexpected token

### ISSUE THREAD

**Issue by LaravDev** [creativetimofficial/ct-vue-material-dashboard-pro#15]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Compile with no errors

# Current Behavior

Getting Syntax Error: unexpected token, so it's not compiling with npm run dev

* Operating System: CENTOS 7
* Browser and Version: Chrome Latest

So, i'm trying to install the template on Laravel, but whenever i try to compile, i got this errors:

Can anyone help me to set this up correctly?

<img width="885" alt="screen shot 2018-09-13 at 1 31 57 am" src="https://user-images.githubusercontent.com/35145882/45473825-4d01b380-b6f5-11e8-9ccc-68a9a735d667.png">

**Comment by dragosct10** [comment]
Hi, @LaravDev! Thank you for using our products. Did you try to put a space between the arrow and the word import to look like the below constants? 

Regards, 
Dragos

**Comment by LaravDev** [comment]
Hi, @dragosct10! yes i did it, but i got the same result :(

**Comment by dragosct10** [comment]
Hi! Please try to import the components like this: 

```js
import Dashboard from '@/pages/Dashboard/Dashboard.vue'
```

Regards, 
Dragos

**Comment by LaravDev** [comment]
> Hi! Please try to import the components like this:
> 
> ```js
> import Dashboard from '@/pages/Dashboard/Dashboard.vue'
> ```
> 
> Regards,
> Dragos

Yup, that way worked, i had to check some of the dependencies are a little wrong, i had to install and check which are compatible to make it work, for example if i install any of these, downgrades my webpack version to version 3.* but i have modules that require version 4... and now looks like everything is working except the async maps, and the fullcalendar

**Comment by LaravDev** [comment]
<img width="1440" alt="screen shot 2018-09-14 at 8 46 28 am" src="https://user-images.githubusercontent.com/35145882/45557413-c636fe80-b7fa-11e8-92fc-e534bd37adba.png">

**Comment by LaravDev** [comment]
Ok, there is a typo error in the fullcalendar .scss file, thats why it's not loading styles... when it's called like this:

<img width="371" alt="screen shot 2018-09-15 at 12 34 54 am" src="https://user-images.githubusercontent.com/35145882/45583420-5cad0380-b87f-11e8-9d1a-5ad119a41485.png">

@import "md/plugins/fullCalendar"; //(in your files is called with capital C, but the file is called:

<img width="491" alt="screen shot 2018-09-15 at 12 35 13 am" src="https://user-images.githubusercontent.com/35145882/45583433-7f3f1c80-b87f-11e8-9c16-214c737a3eda.png">

@import "md/plugins/fullcalendar"; //this way works


BTW, i changed back to the old way of import, i think it was a missing dependency... now it's getting closer to work this template.
