### ISSUE TITLE
Wizard - Form Data Submission

### ISSUE THREAD

**Issue by tfmccomas** [creativetimofficial/ct-vue-material-dashboard-pro#17]
The Wizard isn't submitting the form, nor does it seem to be collecting the data across all three tabs for submission. I've noticed that the wizardComplete() method isn't being used. 

Am I missing something here? I thought it was functional on the demo... I combed the docs to no avail. Thanks in advance!

**Comment by tfmccomas** [comment]
Never mind. I just figured it out. :-)

**Comment by LaravDev** [comment]
Can you share what you did to solve it?
