### ISSUE TITLE
"Minimize" sidebar after click on a router-link

### ISSUE THREAD

**Issue by LaravDev** [creativetimofficial/ct-vue-material-dashboard-pro#18]
Can you please tell me how to minimize the sidebar after the user clicks on any link, let's say i want to go to the main dashboard, if i click on the sidebar link, the sidebar keeps open, i want to close the sidebar after the click, so the user can see the content right away.

Thanks in advance

**Comment by LaravDev** [comment]
Never mind, i did it already, for anyone looking for the same:

The sidebar nav links that wont close the navbar on mobile when a link is clicked, are:
UserMenu.vue, and MobileMenu.vue

In order to make it work as the other links, just add this to your methods lets say in UserMenu.vue

`toggleSidebar () {
                if (this.$sidebar.showSidebar) {
                    this.$sidebar.displaySidebar(false)
                }
            }`

then in `<collapse-transition>` is a div, you need to add this to the div options:

`<div v-show="!isClosed" :class="{content: !$route.meta.hideContent}" @click="toggleSidebar">`

And that's it.

@dragosct10  i think you should add this to the next update, since sidebar links should hide after the user clicks on any option.

**Comment by dragosct10** [comment]
Hi, @LaravDev! Thank you for this suggestion. We will analyze this and if everything is fine we will add to the next update. 

Regards, 
Dragos
