### ISSUE TITLE
grid view documentation 

### ISSUE THREAD

**Issue by sumitg-3767** [creativetimofficial/ct-vue-material-dashboard-pro#19]
Thank  you for such amazing library. 

I am planning to include vue-material-dashboard pro soon, unlikely I am unable to find documentation for grid system [here](https://demos.creative-tim.com/vue-material-dashboard-pro/documentation/). 
Can you please confirm if there exist a documentation or not ? 
Is it any how dependent on bootstrap ?

**Comment by dragosct10** [comment]
Hi, @sumitg-3767! Thank you for using our products. The documentation for grid system is located on the vuematerial.io site. Please see this [link](https://vuematerial.io/ui-elements/layout).

Regards, 
Dragos

**Comment by sumitg-3767** [comment]
Thank you Dragos. That was helpful !
