### ISSUE TITLE
Animated-number, does not accept formatted numbers

### ISSUE THREAD

**Issue by LuanFreitas** [creativetimofficial/ct-vue-material-dashboard-pro#20]
# Expected Behavior
Formatted number inside animated-number

# Current Behavior
When we put some number with format, the component will only show part of the number.
Ex.: passing "234.567" the dashboard will show only "234"

What is the current behavior?
Describer above.
We saw in the documentation that formatted number's works if we split the value in 2 (or more) pieces and create an html tag for each one, but this is not the expected behaviour.

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.
1. Add an animated-number putting formatted number inside it (ex: 123.456)
2. Only the left part of the number will appear
3. you get it...

## Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: macbook pro
* Operating System: mac os 10.14
* Browser and Version: chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by dragosct10** [comment]
Hi, @LuanFreitas! Thank you for using our products. Please add this version of the tween.js in your package.json `"@tweenjs/tween.js": "^17.2.0"` and run npm install. After that please go the src/components/AnimatedNumber.vue component and make that the method looks like this: 

```js
initAnimation(newValue, oldValue) {
        let vm = this

        function animate() {
          if (TWEEN.update()) {
            requestAnimationFrame(animate)
          }
        }

        new TWEEN.Tween({tweeningNumber: oldValue})
          .easing(TWEEN.Easing.Quadratic.Out)
          .to({tweeningNumber: newValue}, this.duration)
          .onUpdate(function (object) {
            vm.animatedNumber = object.tweeningNumber.toFixed(0)
          })
          .start()

        animate()
      }
```

Regards, 
Dragos

**Comment by LuanFreitas** [comment]
Thank you! I did what you asked for. I had to also change this snippet of code:
**After**
`.onUpdate(function (object) {
            vm.animatedNumber = object.tweeningNumber.toFixed(0)
          })`
**Before**
`.onUpdate(function (object) {
            vm.animatedNumber = object.tweeningNumber
          })`

Doing all this solved the problem 😄
