### ISSUE TITLE
installation instruction missing in the documentation

### ISSUE THREAD

**Issue by sumitg-3767** [creativetimofficial/ct-vue-material-dashboard-pro#21]
Thanks for the wonderful library. We have purchased this theme and were planning to use it in our existing vue.js project, however unlikely we are unable to find the correct way to install this library. All we got is a zip file with components. Can you please suggest a proper way to install this library in existing vuejs project? We would also be looking forward to receive bug fixes if any, please suggest how would the bug fixes be updated to our project.

**Comment by dragosct10** [comment]
Hi! Ok, now I understand what you mean, sorry my bad. Unfortunately, we don't have instructions on how to install this product inside of an existing project, and I must admit that you are the first one who asks for that kind of instructions, but it is a good feature for us and we will add some steps in the future in the docs. Now our advise it will be first to take all the scss and put it in your project, after that install on your project the vuematerial.io framework and then take what components do you need from vue material dashboard pro and put inside your project. 

Hope these pieces of information will help you!

Regards, 
Dragos

**Comment by sumitg-3767** [comment]
Thanks Dragos,

I found a workaround for the same, unfortunately there are lot of things missing. 

i.e. documentation for **notification on click without icon**
Given [doc](https://demos.creative-tim.com/vue-material-dashboard-pro/documentation/component-docs/notifications.html) here does not help at all. I wish you guys could improve on documentations. Documentation is the base for a product to grow.

**Comment by dragosct10** [comment]
Hi, @sumitg-3767! Thank you for your feedback we will definitely take this in consideration. 

Regards, 
Dragos

**Comment by normic** [comment]
Hi @dragosct10,
We're also in the process of implementing a dashboard into our existing vue app. I just downloaded the Material Dashboard to give it a try. But unfortunately I cannot find any information how to implement this.

We're looking for a way to implement a dashboard (preferably yours) into our app and of course to keep it updated in the future. Your mentioned way looks not that straightforward to me. Shouldn't keep things easily on the run in the long way be like updating a plugin?

Can you tell us if there is a recommended way of 
a) implementing the dashboard into an existing app?
b) keep it updated in the future?

If this will be only possible in the Pro or Developer version, simply let me know.

Thanks in advance.

Regards,
normic

**Comment by dragosct10** [comment]
Hi, @normic! Thank you for using our products. Please see the [documentation](https://demos.creative-tim.com/vue-material-dashboard-pro/documentation/), we always have something like getting started in our docs of the products. Our products are maintained always to the latest versions, so you will be able to take always the updates that we are making for you. To implement the product inside of an existent vue app you can just copy our assets and integrate the vue-material framework and then you can take components from our product and implement in yours. 

Hope these pieces of information will be helpful for you! 

Regards,
Dragos

**Comment by NotMyself** [comment]
I'll make this the third request for detailed instructions for integrating with an existing vue.js application. The getting started guide is of no help.
