### ISSUE TITLE
md-select adds flicker when selecting

### ISSUE THREAD

**Issue by sumitg-3767** [creativetimofficial/ct-vue-material-dashboard-pro#23]
using md-select as shown on the documentation page. 
When selecting the dropdown it add a temporary horizontal scrollbar and removed it immediately. 
Please see the attached screenshot below
![dropdownflicker](https://user-images.githubusercontent.com/7676130/46902536-cfdc8080-cee4-11e8-9088-30edf81c2a08.gif)

**Comment by dragosct10** [comment]
Hi, @sumitg-3767! To fix this issue please go to `src/assets/scss/md/_select.scss` and add at the bottom of the partial the following code: 

```css
.md-menu.md-select {
  overflow: hidden;
}
```

This will fix that scroll! 

Regards, 
Dragos
