### ISSUE TITLE
How to fixed sidebar?

### ISSUE THREAD

**Issue by l02162010** [creativetimofficial/ct-vue-material-dashboard-pro#25]
Hello!
How to fixed sidebar?

**Comment by dragosct10** [comment]
Hi, @l02162010! Thank you for using our products. Please be more specific about what you want. 

Regards, 
Dragos

**Comment by dragosct10** [comment]
Hi! To make this you have to go to in folder public/index.html and there put on the tag body the class `sidebar-mini`. 

Regards,
Dragos
