### ISSUE TITLE
tag in table bug

### ISSUE THREAD

**Issue by l02162010** [creativetimofficial/ct-vue-material-dashboard-pro#27]
if tags in the table, tag's icon will change.

this is not in the table
<img width="833" alt="2018-10-22 2 30 19" src="https://user-images.githubusercontent.com/14830189/47280113-5e4cb280-d607-11e8-8e78-0f054dc5863b.png">

this is in the table
<img width="814" alt="2018-10-22 2 30 27" src="https://user-images.githubusercontent.com/14830189/47280117-64429380-d607-11e8-9804-08e57a320acd.png">

how to fix it?

**Comment by dragosct10** [comment]
Hi! The icon tag it's not changing. Actually the icon it's moving to the right and I can't figure why, but if you will put a position:relative and a left: -5px the icon will be on a good position. Regards, Dragos
