### ISSUE TITLE
why in any page after refreshing F5 or Ctrl-R to show 404 error page?

### ISSUE THREAD

**Issue by erkinuzz** [creativetimofficial/ct-vue-material-dashboard-pro#28]
it is a bug? or how to fix it?

**Comment by dragosct10** [comment]
Hi, @erkinuzz1 Thank you for using our products. I already answered you on our site comments area. We tested and the product it's working fine in our side. Did you test on more devices? Regards, Dragos

**Comment by erkinuzz** [comment]
Oh thanks! I think it is a nginx side problem
