### ISSUE TITLE
keep sidebar open

### ISSUE THREAD

**Issue by airguide** [creativetimofficial/ct-vue-material-dashboard-pro#3]
How can you keep the sidebar open when the dashboard loads firsttime

**Comment by dragosct10** [comment]
Hi, @airguide! Thank you for using our product. You can easily do that by simply going to the index.html page and remove the class `.sidebar-mini` from the body tag. 

Regards, 
Dragos

**Comment by airguide** [comment]
Hello Dragos, thanks that did the trick
