### ISSUE TITLE
<md-autocomplete> Any plans to include this?

### ISSUE THREAD

**Issue by LaravDev** [creativetimofficial/ct-vue-material-dashboard-pro#31]
Hi, guys, i'm wondering if you are planing to support <md-autocomplete> it would be really usefull, or if it's possible to use it now, can you show me how?

**Comment by dragosct10** [comment]
Hi, @LaravDev! Thank you for using our products. The `md-autocomplete` it's already in the project included in the navbar on that search from. 

Regards, 
Dragos
