### ISSUE TITLE
Is there any way to use notifications in js file ?

### ISSUE THREAD

**Issue by Thyiad** [creativetimofficial/ct-vue-material-dashboard-pro#32]
Hi, is there any way to use notifications in js file ?
like this: 
`
export const toast = (msg, type)=>{
    notify(options)  // here use notification, other js file and view use this method
}
`

**Comment by Thyiad** [comment]
I just find an way to use it.
export NotificationStore from NotificationPlugin/index.js
and then use NotificationStore.notify

**Comment by Thyiad** [comment]
This template is so beautiful, I can't help but buy my first template.

**Comment by dragosct10** [comment]
Hi, @Thyiad! Thank you for using our products and for the kind words. We are glad that you find this way to use notifications. If you need more help please tell us! 

Regards, 
Dragos

**Comment by ahmadshahrour951** [comment]
@dragosct10 Hey man, I was wondering if there's a way to do it officially? (rather than hacking the plugin?)

**Comment by dragosct10** [comment]
Hi, @ahmadshahrour951! Thank you for using our products. We need to look deeper into finding a solution, but for the moment this is the only solution. 

Thank you for your understanding! 

Regards, 
Dragos
