### ISSUE TITLE
Where is the loading style

### ISSUE THREAD

**Issue by Thyiad** [creativetimofficial/ct-vue-material-dashboard-pro#33]
Hi, I can't find the loading style.
Used for when ajax or other actions that want show an overlay with a tip or icon.
Is there no style for loading?

**Comment by dragosct10** [comment]
Hi, @Thyiad! You're talking about this [progress spinner](https://vuematerial.io/components/progress-spinner), right? 

Regards, 
Dragos

**Comment by Thyiad** [comment]
Hi, is that mean I need packaged into an component, not like other library [loading](http://element-cn.eleme.io/#/en-US/component/loading), alreay provided.

**Comment by Thyiad** [comment]
I also can import other loading library, but really want supported in this template...

**Comment by dragosct10** [comment]
Hi! The style loader have already the background color based on the primary color of our product and you can use it or you can customise like you want the component. 

Regards, 
Dragos

**Comment by Thyiad** [comment]
I mean is something like 
https://github.com/ankurk91/vue-loading-overlay
Does it will be provided?

**Comment by dragosct10** [comment]
Hi, @Thyiad! All the spinners that you can use for the moment are here https://vuematerial.io/components/progress-spinner. Maybe in a future update, we can add this new spinner with overlay. 

Regards, 
Dragos

**Comment by Thyiad** [comment]
OK, Thank you. Now I will add a overlay myself.
