### ISSUE TITLE
Project is not compiling

### ISSUE THREAD

**Issue by visaru** [creativetimofficial/ct-vue-material-dashboard-pro#35]
Hi

Project is not compiling. I'm running latest node,npm,macOS all stable releases.

Here is the log after I did `npm run install:clean`

Syntax Error: SyntaxError: /Users/pathto/project/src/routes/routes.js: Support for the experimental syntax 'dynamicImport' isn't currently enabled (8:20):

   6 |
   7 | // Pages
>  8 | const User = ()=>  import('@/pages/Dashboard/Pages/UserProfile.vue');
     |                    ^
   9 | const Pricing = ()=>  import('@/pages/Dashboard/Pages/Pricing.vue');
  10 | const TimeLine = ()=>  import('@/pages/Dashboard/Pages/TimeLinePage.vue');
  11 | const RtlSupport = ()=>  import('@/pages/Dashboard/Pages/RtlSupport.vue');

Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing.

@  ./src/main.js 8:0-37 14:2-8
 @  multi (webpack)-dev-server/client?http://192.168.0.200:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

============================================================
tried to add a .babelrc file and the @babel/plugin-syntax-dynamic-import plugin but is showing more errors more plugins to install etc.

**Comment by dragosct10** [comment]
Hi, @visaru! Thank you for using our products. Please, tell us if you run the latest version of the product which is `1.0.1`? 

Regards, 
Dragos

**Comment by visaru** [comment]
Yes I'm running 1.0.1 the latest, I've bought it yesterday and downloaded yesterday

**Comment by visaru** [comment]
@dragosct10 I managed to get it working by adding a .babelrc file and putting the content:
`
{
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
`
also had to install these to plugins:

npm install --save-dev @babel/plugin-syntax-dynamic-import
npm install --save-dev @babel/plugin-proposal-object-rest-spread

The project is running but I have many eslint errors and/or warnings,

**Comment by dragosct10** [comment]
Hi! It's very weird because the @babel/plugin-syntax-dynamic-import was already installed. This week we will do an update on this product and we will fix all these problems. 

Regards, 
Dragos
