### ISSUE TITLE
Chartist not populating

### ISSUE THREAD

**Issue by LaravDev** [creativetimofficial/ct-vue-material-dashboard-pro#36]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

I'm getting a json response from my server with laravel, and i'm trying to fill the chartist values with it, it should get rendered but nothing is shown.

so, this is how it looks the initial data in my component:

```
dailySalesChart: {
                data: {
                    labels: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                    series: [[]]
                },
                options: {
                    lineSmooth: this.$Chartist.Interpolation.cardinal({
                        tension: 0
                    }),
                    low: 0,
                    high: 2000, // creative tim: we recommend you to set the high sa the biggest value + something for a better look
                    chartPadding: {
                        top: 0,
                        right: 1,
                        bottom: 0,
                        left: 1
                    }
                }
            }
```

So i populate the array getting exactly 12 values from my server and push each of them with a forEach, 

```
created () {
        let self = this
        axios.post('/user/dashboard/stats').then(response => {
            if (response.data.length !== 0) {
                console.log(response.data)

                let data = response.data

                data.forEach(function(e) {
                    self.dailySalesChart.data.series[0].push(Number(e.income_month))
                });
                self.yearTotal = 8999;
                console.log(self.dailySalesChart.data)
            }
        })
    },
```

in my console i can see the data is there, and seems ok to me:

<img width="595" alt="screen shot 2018-11-04 at 11 12 05 am" src="https://user-images.githubusercontent.com/35145882/47967410-8c2bf100-e022-11e8-836e-e92d238d7267.png">

but the chart is empty:

<img width="810" alt="screen shot 2018-11-04 at 11 13 21 am" src="https://user-images.githubusercontent.com/35145882/47967416-b087cd80-e022-11e8-82e4-1eabe5f88fcc.png">

Any hints?

**Comment by dragosct10** [comment]
Hi, @LaravDev! Do you have any errors in your console? 

Regards,
Dragos

**Comment by LaravDev** [comment]
@dragosct10, no errors at all, but i solve it, by adding a timeout with v-if to the chart, somehow the chart loaded even before the created(), or beforeCreate() flow, so because series was empty and not populated, was blank, and also seems like this data is not reactive, so i can't change the charts on the go, i had to make it wait to load, so it get's populated before the chart is rendered.

Do you think you could find out how to make this better?

also, i would really suggest you to use AMCharts, is open source, and looks much better, i miss the on hover labels like you did with other admin dashboards without vue, it's very poor informative the way this charts are right now.

**Comment by xzuvel** [comment]
I have exactly the same problem :(

**Comment by LaravDev** [comment]
@xzuvel so you solve it that way? hmm looks better than my approach actually!

**Comment by dragosct10** [comment]
Hi, @LaravDev! I think it's a simple fix and efficient. Regard to the AMCharts, thank you for the suggestion the plugin really looks nice, but for the moment we are using in our future products and also we want to do updates to the actual products with [Chart.js](https://github.com/chartjs/Chart.js) because it's also a very powerful plugin with more than 40k stars and is growing. 

Regards, 
Dragos

**Comment by xzuvel** [comment]
> @xzuvel so you solve it that way? hmm looks better than my approach actually!

Yes! Sadly its not the best approach :(

**Comment by LaravDev** [comment]
@dragosct10 yes Chart.js is another amazing option, i loved in the Now Ui Dashboard, and prefer that one than this one.

**Comment by LaravDev** [comment]
@dragosct10 is there any plan to change the charts for another component or plugin in the next update?

**Comment by dragosct10** [comment]
Hi, @LaravDev! Sorry for the late response. I have to discuss with the board about this changing because it's an important change, so until we discuss I can't tell you exactly if will be a change like this or not. 

Regards, 
Dragos

**Comment by tyty9798123** [comment]
Great! just add v-if on the chart-card.
