### ISSUE TITLE
Table with Checkboxes. When selecting the checkbox, the md-selected event does not occur!

### ISSUE THREAD

**Issue by antonsmolko** [creativetimofficial/ct-vue-material-dashboard-pro#37]
![2018-11-09_19-46-03](https://user-images.githubusercontent.com/20865516/48283100-8f810b80-e46c-11e8-90d4-ecfeaa3e7e9b.png)

![2018-11-09_19-46-47](https://user-images.githubusercontent.com/20865516/48283043-62ccf400-e46c-11e8-83d5-8b836fcb29d1.png)

![2018-11-09_19-48-57](https://user-images.githubusercontent.com/20865516/48283090-86903a00-e46c-11e8-8ca2-2044040d17af.png)

[screencast 2018-11-09 19-51-07.mp4.zip](https://github.com/creativetimofficial/ct-vue-material-dashboard-pro/files/2567213/screencast.2018-11-09.19-51-07.mp4.zip)

**Comment by antonsmolko** [comment]
And when you cancel selection, then md-selected works!

**Comment by Thyiad** [comment]
@antonsmolko Do you resolve it? If use dev branch will fix it?
