### ISSUE TITLE
md-select multiple is error

### ISSUE THREAD

**Issue by Thyiad** [creativetimofficial/ct-vue-material-dashboard-pro#38]
The md-select multiple prop has [issue](https://github.com/vuematerial/vue-material/issues/1742).

But why the [document](https://demos.creative-tim.com/vue-material-dashboard-pro/documentation/component-docs/select.html#simple-select) works well ?

I just want to use multiple select and find this..

**Comment by dragosct10** [comment]
Hi, @Thyiad! Thank you for using our products. Did you have any error with the md-select? 

Regards, 
Dragos

**Comment by Thyiad** [comment]
Yes，same as the issue。md-select source code has error.
Why your document multiple select work fine..

**Comment by dragosct10** [comment]
Hi! We haven't made anything special for this component to work, we just put the code from the vuematerial.io and it worked. It also works on the Extended Forms page in the project. 

Regards, 
Dragos

**Comment by Thyiad** [comment]
![image](https://user-images.githubusercontent.com/3324812/48762806-c9f96c80-ece6-11e8-89a2-a1cfd81415d3.png)
![image](https://user-images.githubusercontent.com/3324812/48762902-05943680-ece7-11e8-9145-2f0520951b16.png)

**Comment by dragosct10** [comment]
This error's from the vuematerial.io so it's not from our components. Like I told you we don't do anything special to make this working. Do you add extra code for the component or the code for the component it's the same as when you opened first time the project?  I think for the moment to fix this you must follow the steps from the link that you gave us with the same issue opened on vuematerial.io repo. 

Regards, 
Dragos

**Comment by Thyiad** [comment]
Thank you. I did nothing, just add multiple prop.
vuematerial owner seems to be very busy, there is no merge code yet.
I will try to fork and modify it local..
