### ISSUE TITLE
Tabs contents is not showing

### ISSUE THREAD

**Issue by eyalge-262** [creativetimofficial/ct-vue-material-dashboard-pro#39]
# Expected Behavior
The Tabs component should show tabs headers/buttons and tab content.

# Current Behavior
Using the Tabs component shows the tabs headers/buttons but not the tab content.

# Failure Information (for bugs)

You can see it in the Panels demo as well:
https://demos.creative-tim.com/vue-material-dashboard-pro/#/components/panels

## Failure Logs

No logs

**Comment by dragosct10** [comment]
Hi, @eyalge-262! Thank you for using our products. Yes, you're right we will fix it immediately. Regards, Dragos

**Comment by dragosct10** [comment]
Hi! Now it's fixed. Please download again the product. 

Regards, 
Dragos

**Comment by dragosct10** [comment]
Hi, @murilolopes! Thank you for using our products. I will put two images that shows what we changed in the `src/components/Tabs.vue` to make it work. 

before update: 

![screenshot 2018-12-03 at 10 33 28](https://user-images.githubusercontent.com/17456857/49362397-580e2380-f6e7-11e8-973d-7509fc68e65d.png)

after update: 

![screenshot 2018-12-03 at 10 33 40](https://user-images.githubusercontent.com/17456857/49362410-63614f00-f6e7-11e8-8196-a42050ba8cef.png)

Regards,
Dragos
