### ISSUE TITLE
Vue Material Dashboard PRO probelme scorling and taptouch

### ISSUE THREAD

**Issue by adnensisa** [creativetimofficial/ct-vue-material-dashboard-pro#4]
Hello ,

i have probelme with the   tempalte pro Vue Material Dashboard PRO ,but it hase a probelme with scorling and  not responsive 

i have this message error :
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
perfect-scrollbar.jquery.min.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
r.bind @ perfect-scrollbar.jquery.min.js:2
o.bind @ perfect-scrollbar.jquery.min.js:2
r @ perfect-scrollbar.jquery.min.js:2
e.exports @ perfect-scrollbar.jquery.min.js:2
(anonymous) @ perfect-scrollbar.jquery.min.js:2
e.exports @ perfect-scrollbar.jquery.min.js:2
(anonymous) @ perfect-scrollbar.jquery.min.js:2
each @ jquery.min.js:128
each @ jquery.min.js:53
t.fn.perfectScrollbar @ perfect-scrollbar.jquery.min.js:2
(anonymous) @ material-dashboard.min.js?v=2.0.2:1
perfect-scrollbar.jquery.min.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
r.bind @ perfect-scrollbar.jquery.min.js:2
o.bind @ perfect-scrollbar.jquery.min.js:2
r @ perfect-scrollbar.jquery.min.js:2
e.exports @ perfect-scrollbar.jquery.min.js:2

**Comment by dragosct10** [comment]
Hi, @adnensisa! Thank you for using our products. Please, tell us which functions or code did you add to your project? 

Regards, 
Dragos

**Comment by dragosct10** [comment]
Please add this script to the `public/index.html` to the end of the body tag: 

```html
<body class="sidebar-mini">
    <div id="app"></div>
    <!-- built files will be auto injected -->
    <script type="text/javascript" src="https://unpkg.com/default-passive-events"></script>
  </body>
```

Regards,
Dragos

**Comment by LaravDev** [comment]
@dragosct10 

adding this: <script type="text/javascript" src="https://unpkg.com/default-passive-events"></script>

makes an error to come out with fullcalendar: **Unable to preventDefault inside passive event listener invocation.**

please check this and tellme if there is any way to solve it

**Comment by dragosct10** [comment]
Hi, @LaravDev! I think you can remove that script and for better performances instead of this script, you can use from vuejs their [event modifiers](https://vuejs.org/v2/guide/events.html#Event-Modifiers). 

Regards,
Dragos
