### ISSUE TITLE
error options of undefined

### ISSUE THREAD

**Issue by hern12** [creativetimofficial/ct-vue-material-dashboard-pro#40]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Web not show error
![error](https://user-images.githubusercontent.com/13413078/48965454-00d5c800-eff0-11e8-85f7-89a1b58742ae.PNG)

# Current Behavior

After I npm install and run dev I got error like this Error in render: "TypeError: Cannot read property 'options' of undefined" found in AuthLayout.vue

**Comment by dragosct10** [comment]
Hi! Please take the latest version. We fixed this. 

Regards, 
Dragos

**Comment by LaravDev** [comment]
@dragosct10 is there a new version? i just got this error also, but i'd like to know each specific changes, where is this error located?, i have many vue components modified to my own needs, i'd like to know what exactly to update, and not just everything

**Comment by dragosct10** [comment]
Hi, @LaravDev! Don't worry, it was a small update on the package.json where we replace all the versions of the dependencies for example `"^3.0.1"` with `"3.0.1"`. That sign `^` caused the problem with that error because when the user type in console the npm install command, that sign updates the package at the latest version and that it's not ok because like you see could cause problems for the product. 

Regards, 
Dragos

**Comment by LaravDev** [comment]
what packages are causing conflicts on latest updates?

**Comment by hern12** [comment]
thanks a lot Dragosct10

**Comment by LaravDev** [comment]
@dragosct10 i have the same versions of packages as the latest update of vue-material, but still have the error, also i removed the ^ on each... any ideas?

**Comment by dragosct10** [comment]
@LaravDev Yes, we have the changelog in our products but you are right now it's not so intuitive so next time we will put more solid changelogs. About your question, we don't know exactly, but we thought that the problem was from vue-router.

**Comment by dragosct10** [comment]
Please remove the package.lock and node_modules and type npm install again. 

Regards, 
Dragos

**Comment by LaravDev** [comment]
@dragosct10 i did it that way and still the same issue, i have `"vue-router": "3.0.1"` right now which is the same as the upadted vue-material version

**Comment by LaravDev** [comment]
`{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "instaclean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm run dev"
    },
    "devDependencies": {
        "axios": "0.18",
        "babel-loader": "7.1.5",
        "bootstrap": "4.1.3",
        "chartist": "0.11.0",
        "cross-env": "5.2.0",
        "es6-promise": "4.2.5",
        "file-loader": "1.1.11",
        "google-maps": "3.3.0",
        "jquery": "3.3.1",
        "laravel-mix": "2.1.14",
        "lodash": "4.17.11",
        "popper.js": "1.14.4",
        "sass-loader": "7.1.0",
        "vue": "2.5.17",
        "vue-clickaway": "2.2.2",
        "vue-loader": "14.2.3",
        "vue-material": "1.0.0-beta-10.2",
        "vue-router": "3.0.1"
    },
    "dependencies": {
        "@tweenjs/tween.js": "17.2.0",
        "babel-plugin-syntax-dynamic-import": "6.18.0",
        "babel-preset-vue-app": "2.0.0",
        "fullcalendar": "3.9.0",
        "fuse.js": "3.3.0",
        "jvectormap-next": "3.0.0",
        "moment": "2.22.2",
        "moment-timezone": "0.5.23",
        "node-sass": "4.10.0",
        "nouislider": "12.1.0",
        "npm": "6.4.1",
        "perfect-scrollbar": "1.4.0",
        "sweetalert2": "7.29.0",
        "timezones-countries-keywords": "0.0.3",
        "vee-validate": "2.1.2",
        "vue-axios-interceptors": "0.2.1",
        "vue-currency-filter": "3.1.0",
        "vue-loading-overlay": "3.1.0",
        "vue-moment": "4.0.0",
        "vue-template-compiler": "2.5.17",
        "vue-tour": "1.1.0",
        "vue2-transitions": "0.2.3"
    }
}
`

this is my package.json file

**Comment by LaravDev** [comment]
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "instaclean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm run dev"
    },
    "devDependencies": {
        "axios": "0.18",
        "babel-loader": "7.1.5",
        "bootstrap": "4.1.3",
        "chartist": "0.11.0",
        "cross-env": "5.2.0",
        "es6-promise": "4.2.5",
        "file-loader": "1.1.11",
        "google-maps": "3.3.0",
        "jquery": "3.3.1",
        "laravel-mix": "2.1.14",
        "lodash": "4.17.11",
        "popper.js": "1.14.4",
        "sass-loader": "7.1.0",
        "vue": "2.5.17",
        "vue-clickaway": "2.2.2",
        "vue-loader": "14.2.3",
        "vue-material": "1.0.0-beta-10.2",
        "vue-router": "3.0.1"
    },
    "dependencies": {
        "@tweenjs/tween.js": "17.2.0",
        "babel-plugin-syntax-dynamic-import": "6.18.0",
        "babel-preset-vue-app": "2.0.0",
        "fullcalendar": "3.9.0",
        "fuse.js": "3.3.0",
        "jvectormap-next": "3.0.0",
        "moment": "2.22.2",
        "moment-timezone": "0.5.23",
        "node-sass": "4.10.0",
        "nouislider": "12.1.0",
        "npm": "6.4.1",
        "perfect-scrollbar": "1.4.0",
        "sweetalert2": "7.29.0",
        "timezones-countries-keywords": "0.0.3",
        "vee-validate": "2.1.2",
        "vue-axios-interceptors": "0.2.1",
        "vue-currency-filter": "3.1.0",
        "vue-loading-overlay": "3.1.0",
        "vue-moment": "4.0.0",
        "vue-template-compiler": "2.5.17",
        "vue-tour": "1.1.0",
        "vue2-transitions": "0.2.3"
    }
}

this is my package.json file

**Comment by dragosct10** [comment]
Please, tell me which version node did you have? Verify please in your console with `node -v`. It's very weird because I test it on multiple laptops and the error it's not showing anymore.

**Comment by LaravDev** [comment]
i have node v10.13.0

**Comment by dragosct10** [comment]
@LaravDev Please download a fresh copy again of our product from your account and run it and see if with a fresh product without changes everything it's working fine. 

Regards, 
Dragos

**Comment by LaravDev** [comment]
@dragosct10 i have installed on local a fresh copy, and also i installed all other packages just as in my server, and works perfect, but on my production server it's not working, i already tried changing Node version to 8.11.4, or 10.4.0 or 10.13.0, without any luck, i can't understand what could be possibly wrong, on local, everything works well with all my packages... this happened only after the update, but i don't know what to do now, any ideas?

**Comment by LaravDev** [comment]
@dragosct10 i solve it, it was a matter of the god damn browser cache, specifically from cloudflare, i was caching the page from there, cleaned, and did what you said, and now everything is working again, i think this issue comes from here check this out: https://github.com/vuematerial/vue-material/issues/1977

**Comment by dragosct10** [comment]
Hi! Very nice I'm glad that you fixed it and thank you for finding the reason for the error, so the vue-router 3.0.2 it's in conflict with one of the vuematerial.io component. We have to wait until vuematerial will make an update to fix it. Regards, Dragos

**Comment by nombrekeff** [comment]
For me it was also fixed by downgrading vue-router to `3.0.1`

**Comment by Thyiad** [comment]
@LaravDev @nombrekeff Thanks, i have the same problem.
