### ISSUE TITLE
Tooltips are not showing in Firefox

### ISSUE THREAD

**Issue by eyalge-262** [creativetimofficial/ct-vue-material-dashboard-pro#42]
# Expected Behavior
Hovering over components with Tooltips should show the Tooltip on all browsers

# Current Behavior
Hovering over components with Tooltips is not working when browsing with Firefox

# Failure Information (for bugs)
Seen on Firefox version 63.0.1 (64-bit) but probably happens on later versions as well

## Context
Expected here:
https://demos.creative-tim.com/vue-material-dashboard-pro/#/dashboard
In the product cards at the bottom of the page

**Comment by dragosct10** [comment]
Hi, @eyalge-262! Thank you for using our products. Unfortunately, this issue it's from vuematerial.io and we have to wait until they will fix it. Please check this [link](https://github.com/vuematerial/vue-material/issues/1171).

Regards, 
Dragos
