### ISSUE TITLE
Is there a way to consume component data in modal?

### ISSUE THREAD

**Issue by sumitg-3767** [creativetimofficial/ct-vue-material-dashboard-pro#44]
How to consume component data in modal?

i.e. 
`<component>
<modal>
<template slot="header">
use component data here using {{component.data}}
</template>
....
</modal>
...
</component>`

**Comment by dragosct10** [comment]
Hi, @sumitg-3767! Please tell us what do you want to do more exactly? 

Regards,
Dragos

**Comment by sumitg-3767** [comment]
Hi @dragosct10 
I am trying to call a component method from md-select (which is part of modal). @md-selected does not work to consume component method.

`<component template....
<modal.....
<md-select @md-selected="callComponentMethodFromHereDoesNotWork"...>
</md-select>
</modal></component template>
`
Please let me know if I could provide more information.

**Comment by dragosct10** [comment]
Hi! From what I see in the [vuematerial](https://vuematerial.io/components/select) component API this attribute `@md-selected` it's not there you can control your selected option from `v-model`. 

Regards,
Dragos
