### ISSUE TITLE
No validations for datepicker

### ISSUE THREAD

**Issue by eyalge-262** [creativetimofficial/ct-vue-material-dashboard-pro#45]
Using a datepicker with validations does not work, consider this example:
```html
<md-datepicker
    v-model="form.date"
    data-vv-name="date"
    v-validate= "modelValidations.date"
    required>
    <label>Date</label>
</md-datepicker>
```
It is not validated.

**Comment by dragosct10** [comment]
Hi! Please try to put exactly like we used v-validation in `src/pages/Dashboard/Forms/ValidationForms`. Regards, Dragos
