### ISSUE TITLE
Screen Jumps when selecting

### ISSUE THREAD

**Issue by LaravDev** [creativetimofficial/ct-vue-material-dashboard-pro#48]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed (there is some similar issue but the fix wont work on my issue)
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Selecting from a md-select should just work normal and show the option without any issues

# Current Behavior

md-select is jumping the first time is opened

This happens only on mobile, i'm testing it with an iPhone 8 with latest update, and happens the same on safari or chrome in the iphone.

![ezgif com-optimize](https://user-images.githubusercontent.com/35145882/50349712-5a071d80-0502-11e9-82fb-af011f03a546.gif)

**Comment by dragosct10** [comment]
Hi, @LaravDev! Please, can you give us your link of the project to see what is happening there because in this way only from the video it's hard to see what it's the issue there? Regards, Dragos

**Comment by LaravDev** [comment]
I ended up by using md-autocomplete, and now the issue is about the position of the dropdownlist. here: https://github.com/creativetimofficial/ct-vue-material-dashboard-pro/issues/50
