### ISSUE TITLE
vue material dashboard PRO the scroll does not return top

### ISSUE THREAD

**Issue by tdigitalMX** [creativetimofficial/ct-vue-material-dashboard-pro#49]
I am using vue-material-dashboard-pro. When changing the component in vue-router the scroll does not return top, it remains in the same place as the previous page. 

I already use the scrollBehavior mentioned in the vue-router documentation, but it only works once, and for the next time I change the page, it does not work anymore.

**Comment by dragosct10** [comment]
Hi, @tdigitalMX! Thank you for using our products. We had the same type of issue on another vue project and please see this [issue](https://github.com/creativetimofficial/ct-vue-paper-dashboard-pro/issues/44) to see how to fix it. 

Regards,
Dragos
