### ISSUE TITLE
Cannot change default text color

### ISSUE THREAD

**Issue by zherman91** [creativetimofficial/ct-vue-material-dashboard-pro#5]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

According to the documentation it states that the brand-primary color can be changed however, it always stays purple.

# Current Behavior

Primary text color not changing. 

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Attempt to modify line 28 (per docs) brand-primary color from purple to anything else. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Surface book
* Operating System: Windows 10
* Browser and Version: Chrome - latest

**Comment by dragosct10** [comment]
Hi, @zherman91! Thank you for using our products. Do you opened the `src/assets/scss/md/_variables.scss` and changed the variable `$brand-primary` with any color do you want and then nothing happened? 

Regards,
Dragos

**Comment by zherman91** [comment]
Hi @dragosct10! Thanks for getting back to me. You are correct. I attempted to change it from purple but the change is not taking effect. Could the styles for Vue-Material be overwriting it? If so, do you know of a way to prevent that?

Thanks again. 
Zac

**Comment by zherman91** [comment]
So I believe i fixed the issue. According to the docs, it says to change the brand-primary on line 28 of the _variables file which never took. So, i just tried changing the _colors file and that seems to have taken effect. Thanks for all the replies and trying to help me out. I appreciate it! Keep up the good work!

Zac

**Comment by thyerrimezzari** [comment]
Is there a way to change #brand-primary dynamically via javascript?

**Comment by dragosct10** [comment]
Hi, @thyerrimezzari! JavaScript runs client-side (in the web browser), while Sass is generated server-side, so you have to find some way to bridge that gap. One way to do this would be to set up some AJAX-style listening to send JavaScript events over to your server, and then have the server edit and re-compile your style.sass file.

Regards,
Dragos
