### ISSUE TITLE
MD Autocomplete dropdown list won't stay under the input field

### ISSUE THREAD

**Issue by LaravDev** [creativetimofficial/ct-vue-material-dashboard-pro#50]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When appearing the drowpdown list on the md-autocomplete it should stay under the input field.

# Current Behavior

the dropdown list moves around and won't stick under the field, and if you change the orientation of the phone to landscape nothing is shown, if you change it again to portrait, the look is even worst.

Please help with this!

# Failure Information (for bugs)

you can't reproduce this unless you show a md-autocomplete field on mobile, your demo won't show the search box on mobile, so this issue happens and it's very confusing

* Device: iphone 8
* Operating System: iOS 12
* Browser and Version: Safari on mobile (latest)

<img width="496" alt="screen shot 2018-12-21 at 2 58 04 pm" src="https://user-images.githubusercontent.com/35145882/50363410-17106e80-0531-11e9-8a3b-fcd0b5bf22e9.png">
<img width="495" alt="screen shot 2018-12-21 at 2 58 17 pm" src="https://user-images.githubusercontent.com/35145882/50363411-17106e80-0531-11e9-8cea-cb65efd8f1ba.png">
<img width="494" alt="screen shot 2018-12-21 at 2 58 47 pm" src="https://user-images.githubusercontent.com/35145882/50363413-17a90500-0531-11e9-9e68-8de29bd4aac2.png">
<img width="500" alt="screen shot 2018-12-21 at 2 58 54 pm" src="https://user-images.githubusercontent.com/35145882/50363414-1972c880-0531-11e9-93ba-50ddf34c53c0.png">
<img width="495" alt="screen shot 2018-12-21 at 2 59 21 pm" src="https://user-images.githubusercontent.com/35145882/50363415-1972c880-0531-11e9-94bb-d13ba9d18a47.png">
<img width="495" alt="screen shot 2018-12-21 at 2 59 32 pm" src="https://user-images.githubusercontent.com/35145882/50363416-1a0b5f00-0531-11e9-9f3e-b3e1561a3e4c.png">
<img width="495" alt="screen shot 2018-12-21 at 2 59 41 pm" src="https://user-images.githubusercontent.com/35145882/50363417-1a0b5f00-0531-11e9-8354-e0181181b0c4.png">

**Comment by LaravDev** [comment]
Hi dragos, can you please create a modal with the md-autocomplete and try again to reproduce the issue?, because in my case this is in a SweetAlert modal that happens, also i think this issue is related to the keyboard of the iphone and the space is left in the screen for the dropdown list, if is too small then it will have the issue i showed to you, probably because your iphone x has a larger screen you don't see this happening, so try this inside a sweet alert with a smaller iphone to reproduce it.

**Comment by LaravDev** [comment]
@dragosct10 did you try to reproduce it as i said?

**Comment by dragosct10** [comment]
Hi, @LaravDev! Sorry for the late response but we are not in the office these days. I will try to reproduce what you said and I will let you know. Thank you for your understanding and sorry again! 

Regards, 
Dragos

**Comment by dragosct10** [comment]
Hi! I just tried to reproduce the issue in a modal like you have on your project on a smaller screen on iPhone SE and please see this [link](https://www.dropbox.com/s/7lggn9kxyifoh1t/ScreenRecording_12-31-2018%2013-06-44.MP4?dl=0) to see what is happening. It's weird because I can't reproduce the issue and this I think it's the smallest screen on a smartphone. 

Regards,
Dragos

**Comment by dragosct10** [comment]
Hi! I've made another test with the keyboard opened also on the Iphone SE. Please see this [link](https://www.dropbox.com/s/83mrg8ee2vyspxe/ScreenRecording_01-02-2019%2015-52-35.MP4?dl=0). 

Regards, 
Dragos

**Comment by LaravDev** [comment]
hmmm, weird then, not sure why is happening with my iphone... :S, my modal window is actually a sweet alert modal, maybe happens only with that... :/ anyway, thanks Dragos!
