### ISSUE TITLE
how to clear date input

### ISSUE THREAD

**Issue by hern12** [creativetimofficial/ct-vue-material-dashboard-pro#51]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes ] I am running the latest version
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed
- [ yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
if click X button on date picker should be null or empty string

Please describe the behavior you are expecting
when I click X button on md-datepicker my v-model not null it still the last selected date if I want to get null from date how can I fix this thanks

# Current Behavior
click X button from datepicker do not change current date

![1](https://user-images.githubusercontent.com/13413078/50375791-bfa7f680-0635-11e9-9cf1-45f453fc263e.PNG)
first I add v-model to date picker
![2](https://user-images.githubusercontent.com/13413078/50375792-c0408d00-0635-11e9-8854-cc267b30b09c.PNG)
second I click X button for clear date input value
![3](https://user-images.githubusercontent.com/13413078/50375793-c0408d00-0635-11e9-8daf-bde21164c6ff.PNG)
third I tire to console date after click some button
![4](https://user-images.githubusercontent.com/13413078/50375794-c0408d00-0635-11e9-9da7-3388c6cf87c7.PNG)
last the result still show date

**Comment by dragosct10** [comment]
Hi, @hern12! Thank you for using our products. Unfortunately this issue it's not from our side it's from vuematerial.io. Please see this[ issue](https://github.com/vuematerial/vue-material/issues/1803) which it's the same with what you have here and I think it can help you. Regards, Dragos
