### ISSUE TITLE
how to set prettier ?

### ISSUE THREAD

**Issue by l02162010** [creativetimofficial/ct-vue-material-dashboard-pro#55]
v1.0.1
v1.0.4
the format is different,
how to set prettier, double quote to single quote, and no semicolon?
And how to format all file?
thank you~

-----
by the way, if I want to compare two versions have what different, what can I do?

**Comment by dragosct10** [comment]
Hi, @l02162010! Thank you for using our products. Please see this [link](https://github.com/prettier/eslint-config-prettier) in order to check how to set the prettier. Regard to the last question do you want to compare two versions of this product? 

Regards,
Dragos

**Comment by l02162010** [comment]
@dragosct10 yes, I want to compare this product

**Comment by dragosct10** [comment]
@l02162010, the best way to see the changes between versions is the `CHANGELOG.md` file which it's in your downloaded archive. 

Regards, 
Dragos

**Comment by l02162010** [comment]
<img width="532" alt="2019-01-18 5 07 49" src="https://user-images.githubusercontent.com/14830189/51376583-a5cdd680-1b43-11e9-9ec2-c9ebd7ecdf0f.png">
Actually, CHANGELOG.md that can't show detail information
Other bug fixes => like this, can you give more detail?

**Comment by l02162010** [comment]
right now.
I use Beyond Compare to compare the code.
but, I still want some good way to compare the different version code.
