### ISSUE TITLE
tabs have some problem

### ISSUE THREAD

**Issue by l02162010** [creativetimofficial/ct-vue-material-dashboard-pro#56]
md-content md-tabs-content md-theme-default
it contains a lot of things, but height is 102px
I need to resize my website so, it contains thing will show up
how to fix this bug?

it is before resize
<img width="297" alt="2019-01-18 5 00 41" src="https://user-images.githubusercontent.com/14830189/51376180-aa45bf80-1b42-11e9-83f7-a2f3ec8c5810.png">

it is after resize
<img width="287" alt="2019-01-18 5 04 32" src="https://user-images.githubusercontent.com/14830189/51376422-3e178b80-1b43-11e9-9358-2c2db7ca33af.png">

**Comment by dragosct10** [comment]
@l02162010 , the tab component belongs to vuematerial, so that height it's dynamically from their component. A workaround for this it's to set on `md-tabs-content` a max-height CSS property. 

Regards, 
Dragos

**Comment by l02162010** [comment]
@dragosct10 sorry, I let you miss.
this tab hides my thing, I need this tab show my thing.
so, I want this height dynamically to become 2164px in begin.
how should I do?

**Comment by dragosct10** [comment]
We don't have control on this component because like I said it's a component from vuematerial.io, and you can put a max-height and overflow: auto and then you can scroll for your things. 

Regards, 
Dragos
