### ISSUE TITLE
Error Failed to compile

### ISSUE THREAD

**Issue by robecha18** [creativetimofficial/ct-vue-material-dashboard-pro#57]
Hello, when you deploy the application, the following error is shown in the image. I already installed npm correctly, but at the time of compiling it shows that detail.

![image](https://user-images.githubusercontent.com/14876450/51560394-00b84400-1e4a-11e9-8760-e1e79b51e335.png)

**Comment by dragosct10** [comment]
Hi, @robecha18! Thank you for using our products. Please, tell us before this error you entered the command in the console `npm run build`? This `import "vue-material / dist / vue-material.min.css";` line it's importing the css for the vue material framework from the `node_modules` so this it's not a problem. 

Regards,
Dragos

**Comment by dragosct10** [comment]
Hi, @morgenweck! Thank you for using our products. Did you have the latest version of the product? 

Regards, 
Dragos

**Comment by spola** [comment]
Hello
I have the same problem. I downloaded the version [1.1.0] 2019-01-18 just a minutes ago

**Comment by DOTTH** [comment]
Hi, 

![image](https://user-images.githubusercontent.com/28741209/51848731-df999c80-22fc-11e9-827d-6f059e2f7956.png)

I have the same problem, i tried with the same version  as @spola, please your help!

**Comment by spola** [comment]
I solved my problem installing 2 dev dependencies from node plugins:
    "ajv": "^6.0.0",
    "eslint": "^3.9.0"

After install the plugins a few warnings was showed, all of them from peer dependencies.

I think this wasn't the SOLUTION, but is a good hotfix :)

**Comment by dragosct10** [comment]
Hi! Today we will fix this issue because it's a priority. 

Regards, 
Dragos

**Comment by dragosct10** [comment]
The theme it's updated. Now I will close the issue.

Regards,  
Dragos
