### ISSUE TITLE
The tabs component have bug

### ISSUE THREAD

**Issue by l02162010** [creativetimofficial/ct-vue-material-dashboard-pro#58]
# Prerequisites

- [ 1.0.4 ] I am running the latest version
- [ yes ] I checked the documentation and found no answer

the tabs component add overflow to _tabs.scss, will have a bug like the image
```css
overflow: scroll;
```
the small box

<img width="964" alt="2019-01-31 11 04 38" src="https://user-images.githubusercontent.com/14830189/52100838-272d6a80-2614-11e9-86ff-bdbb51b9bc92.png">
<img width="817" alt="2019-01-31 11 04 48" src="https://user-images.githubusercontent.com/14830189/52100840-2bf21e80-2614-11e9-8ee7-d684b5e85a6d.png">

when I remove overflow in _tabs.scss, will be fine. why?
```css
overflow: scroll;
```

**Comment by dragosct10** [comment]
Hi, @l02162010! We have to investigate this issue and we will come back to you and include it this in the next update. 

Regards, 
Dragos
