### ISSUE TITLE
charts tiny

### ISSUE THREAD

**Issue by fabiobusnellosilvershark** [creativetimofficial/ct-vue-material-dashboard-pro#59]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

when I render a card with graphics, they get tiny as below, I realized that it is something related to the component `<zoom-center-transition: duration =" 200 "mode =" out-in ">` below is an example.
![image](https://user-images.githubusercontent.com/37873929/52445289-d507b000-2b11-11e9-8a0d-980a79cffa51.png)

**Comment by dragosct10** [comment]
Hi, @fabiobusnellosilvershark! Thank you for using our products. To understand better this is happening when your component it's nested in the `zoom-center-transition` component? 

Regards,
Dragos

**Comment by fabiobusnellosilvershark** [comment]
yes, 

Home.vue = http://localhost:8080/home/
![image](https://user-images.githubusercontent.com/37873929/52499239-1a83b600-2bc2-11e9-9569-721c4a300d14.png)

Dashboard.vue = http://localhost:8080/home/dashboard/
![image](https://user-images.githubusercontent.com/37873929/52499395-78180280-2bc2-11e9-922a-51257f459921.png)

**Comment by dragosct10** [comment]
Hi! In the product this transition it's by default included, so as you see also in the demo page everything it's working fine on our side, so we can't reproduce your issue, but as I saw in your images you use a component graphics and It's possible that the graphics cause you the problem. 

Regards,
Dragos
