### ISSUE TITLE
How to use Vue Material Dashboard PRO with Nuxt.js

### ISSUE THREAD

**Issue by sumihiro** [creativetimofficial/ct-vue-material-dashboard-pro#60]
I tried Vue Material Dashboard PRO with Nuxt.js as a plugin.
But I got ```TypeError Cannot redefine property: $sidebar``` error.
How to install to Nuxt.js project?

I copy sources from ```vue-material-dashboard-pro-v1.1.1``` folder to Nuxt.js plugins folder.
Then, I made plugin settings.
After run ```npm run dev```, I tried to access http://localhost:3000/.
At first time, it works great.
But after reloading, I got ```TypeError Cannot redefine property: $sidebar``` error.

Please refer my sample project.
More detail steps are there.

https://github.com/sumihiro/vmd-sample

**Comment by dragosct10** [comment]
Hi, @sumihiro! Thank you for using our products. We really want to help you, but we don't use until now nuxt.js so we don't know how this works and it's hard to give advice about this issue. Look at this [link](https://github.com/nuxt/nuxt.js/issues/138) it seems to be similar like yours and I think this can help you. 

Thank you for your understanding! 

Regards, 
Dragos

**Comment by sumihiro** [comment]
@dragosct10 Thank you!

I know about your link, but it was useless.

Finally, I found my solution.
That is not to use SSR (Server Side Rendering). I use only SPA(Single Page Application).
https://nuxtjs.org/api/configuration-mode

I hope your products will work on SSR as well.
I look forward to future updates.

**Comment by EarthmanWeb** [comment]
Hmm, I was about to buy this theme until I realized here it is not compatible with Nuxt. Thanks for posting this, @sumihiro 

@dragosct10  Do you have nuxt in your roadmap yet?
