### ISSUE TITLE
Integration with webpack

### ISSUE THREAD

**Issue by marek-obuchowicz** [creativetimofficial/ct-vue-material-dashboard-pro#61]
# Expected Behavior
Use webpack directly to build the dashboard

# Current Behavior
Currently dashboard is using vue-cli-service directly. While this is the current default for vue projects, it does not work with most web frameworks not based on npm. There is plenty of major frameworks (like symfony (php), rails (ruby), buffalo (golang)) which provide industry-standard integration with webpack. It would be great if a build process for webpack would be made available. Using standard vue "webpack" template does not provide all the dependencies needed for this template.

**Comment by dragosct10** [comment]
Hi, @marek-obuchowicz! I already answered you on your email. I will close this now.

Regards, 
Dragos
