### ISSUE TITLE
md-datepicker yyyy-mm-dd to dd-mm-yyyy

### ISSUE THREAD

**Issue by irineos1995** [creativetimofficial/ct-vue-material-dashboard-pro#63]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed
- [Yes] I'm reporting the issue to the correct repository (for multi-repository projects)

Hi, the issue is that **there is no ":format" option for "md-datepicker".**
When I pick up a date from the "md-datepicker", **I get it in the form of "yyyy-mm-dd" where I wanna get it in the format "dd-mm-yyyy".**
Are you going to implement that? Or if there is a solution can you please point me to it?

Thank you in advance,
Iri!

**Comment by dragosct10** [comment]
Hi, @irineos1995! Thank you for using our products. Please try to use the format like in this [link](https://codesandbox.io/s/6398yyjqn). 

Regards, 
Dragos

**Comment by irineos1995** [comment]
Hello @dragosct10 . Thank you for your quick reply. for some weird reason, after clicking on the date and then clicking ok the whole website crashes. Is like is getting stuck in a loop or something.

**Comment by dragosct10** [comment]
Hi! It seems like you see in [this](https://github.com/vuematerial/vue-material/issues/1689) issue opened on vue-material that it something related to the vue material framework. 

Regards, 
Dragos

**Comment by irineos1995** [comment]
There is not workaround for it?
Does that mean that we are restricted to the default format which is YYYY-MM-DD 
?

**Comment by dragosct10** [comment]
Hi! Sorry for the late response. For the moment we don't have what to do because the vue-material it's not our framework we just use it and this is a bug from their component, but we still looking for a workaround until vue-material will release a fix for this issue. Thank you for your understanding! 

Regards,
Dragos
