### ISSUE TITLE
md-table headers not aligned in the center of each column

### ISSUE THREAD

**Issue by irineos1995** [creativetimofficial/ct-vue-material-dashboard-pro#64]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Headers of the table to be aligned in the center of each column

# Current Behavior
For example here the column "Telephone" is aligned on the right where the other columns are aligned in the middle of each column.

![image](https://user-images.githubusercontent.com/30058509/53693997-ff126200-3d9f-11e9-93b7-a367b42c7739.png)

**Comment by dragosct10** [comment]
Hi! The last column has the CSS style with text-align right and you must to put text-align center. Please see the updated image. 

<img width="873" alt="screenshot 2019-03-04 at 10 13 56" src="https://user-images.githubusercontent.com/17456857/53719305-62ff5e00-3e66-11e9-92c3-8c314e87986d.png">

Regards,
Dragos

**Comment by irineos1995** [comment]
great. that works for the header. what about the cell?
I tried to find something like last-child{ text-align: right} but couldn't find what leads to that behavior. if you could tell me which file holds that setting. it would be great!

**Comment by irineos1995** [comment]
nevermind. found it in **/vue-material-dashboard-pro-v1.2.0/src/assets/scss/md/_tables.scss** 
under 
`.md-table-cell:last-child .md-table-cell-container,
  .md-table-head:last-child{
    text-align: right !important;
    display: flex;
    justify-content: flex-end;
  }`

and changed it to:
`.md-table-cell:last-child .md-table-cell-container,
  .md-table-head:last-child{
    text-align: center !important;
    display: flex;
    justify-content: center;
  }`
