### ISSUE TITLE
Toolbar and footbar fixed position

### ISSUE THREAD

**Issue by F-Tash** [creativetimofficial/ct-vue-material-dashboard-pro#65]
Hello,
Is it possible to make fixed top toolbar and footbar in fixed position? 
So during scrolling they should be always displayed?

**Comment by dragosct10** [comment]
Hi! Yes, you can add on the `md-toolbar` the css property `position: fixed` and also you can do the same thing for the footer. 

Regards,
Dragos

**Comment by F-Tash** [comment]
Thanks for responding!
I changed md-toolbar position to fixed, but it become transparent and wide,
profile, logout buttons are disapeared:
[image: image.png]

**Comment by dragosct10** [comment]
Hi! You can put on the md-toolbar component a styling class for the background-color from [here](https://demos.creative-tim.com/vue-material-dashboard-pro/documentation/component-docs/toolbar.html#colors). For the footer please add also a `bottom: 0` and `z-index: 9999` to the footer. 

Regards,
Dragos
