### ISSUE TITLE
Not smooth scrolling during scroll with mouse wheel

### ISSUE THREAD

**Issue by F-Tash** [creativetimofficial/ct-vue-material-dashboard-pro#67]
Hello
I'm using latest version of vue material dashboard pro theme, in every page found it is not smooth scrolling with mouse wheel, it is twitching. Sometimes it twiches to opposite side of scrolling. Is it possible to fix it?
 It  can be noticed exactly in http://localhost:8080/#/table-list/extended in last table with pictures.

**Comment by dragosct10** [comment]
Hi, @F-Tash! Thank you for using our products. Please, send us a valid link because you put there localhost and it's not working. Related to the issue on our side everything it's working fine. 

Regards,
Dragos

**Comment by F-Tash** [comment]
Thanks for responding!
Yes, it seems problem was in my pc, in my laptop it's scrolling good.
