### ISSUE TITLE
How i can use notify in main.js file?

### ISSUE THREAD

**Issue by v-pr** [creativetimofficial/ct-vue-material-dashboard-pro#68]
I need catch server error globally in main.js. How i can generate notify in main.js file?
```
Axios.interceptors.response.use(function (response) {
  return response;
}, function (error) {
  if (!error.status) {
    $.notify({
      message:
        $t("server_error"),
      horizontalAlign: "top",
      verticalAlign: "center",
      type: "danger",
    });
  }
  if (error.response.status === 401) {
    Cookies.remove('token');
    router.push({ path: "/access_denied" });
  }
  return Promise.reject(error);
});

**Comment by dragosct10** [comment]
Hi, @v-pr! Thank you for using our products. Please try like in the uploaded image: 

![Screenshot 2019-03-11 at 09 35 14](https://user-images.githubusercontent.com/17456857/54107177-0dd0c880-43e1-11e9-9201-88fabe66ae52.png)

Regards,
Dragos

**Comment by Thyiad** [comment]
@v-pr You may need this [https://github.com/creativetimofficial/ct-vue-material-dashboard-pro/issues/32](url)
according to the source code, just export notifyStor, it will work fine:
![image](https://user-images.githubusercontent.com/3324812/55951916-f3616780-5c8a-11e9-928f-864b7a31f519.png)
