### ISSUE TITLE
Route: table-list/paginated - Error on Action Click

### ISSUE THREAD

**Issue by marcoslisboa** [creativetimofficial/ct-vue-material-dashboard-pro#69]
**Route:** /table-list/paginated

**Description:** Error on Action Click

**Console Error:** 
```javascript
TypeError: Cannot read property 'constructor' of undefined
    at Tt (sweetalert2.all.js:2517)
```

**Possible Solution:** 
Replace Import
```javascript
import swal from 'sweetalert2'
```
to
```javascript
import Swal from 'sweetalert2'
```

And Replace Call:
```javascript
swal({})
```
to
```javascript
Swal.fire({})
```

**Comment by marcoslisboa** [comment]
https://demos.creative-tim.com/vue-material-dashboard-pro/#/table-list/paginated

**Comment by dragosct10** [comment]
Hi, @marcoslisboa! Thank you for using our products and for your observation. You're right this a small and thank you for the solution, we will include this in the next update. 

Regards, 
Dragos

**Comment by marcoslisboa** [comment]
very good!

I keep following the next releases. :+1:
