### ISSUE TITLE
Set locale for datepicker

### ISSUE THREAD

**Issue by LuanFreitas** [creativetimofficial/ct-vue-material-dashboard-pro#7]
I have not found a way to set a locale for the datepicker. Could someone help?

**Comment by dragosct10** [comment]
Hi, @LuanFreitas! Thank you for using our products. Please see [this](https://github.com/vuematerial/vue-material/issues/1310) issue to see how you can access the locales for datepicker. 

Regards, 
Dragos

**Comment by LuanFreitas** [comment]
@dragosct10 thanks guy!!!
