### ISSUE TITLE
autocomplete dropdown. cannot select option without typing anything

### ISSUE THREAD

**Issue by irineos1995** [creativetimofficial/ct-vue-material-dashboard-pro#70]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

should be able to select **md-options without typing anything**

# Current Behavior

selecting an option **without typing anything** does not reflect it.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. [codesandbox](https://codesandbox.io/s/mjrq8o7zvy?module=App.vue)
2. select any country **without typing anything**
3. does not get changed. Is like you haven't clicked on anything

**Comment by irineos1995** [comment]
apparently is fixed in vue-material **dev branch**. can someone please tell me how to use dev branch in my project?
Is it correct to do this: 
- "vue-material": "vuematerial/vue-material#dev" 
in my package.json dependencies?

**Comment by dragosct10** [comment]
Hi, @irineos1995! Thank you for using our products. Please see this [link](https://martinwolf.org/2018/04/github-branch-as-dependency-package-json/), maybe it will help you. 

Regards,
Dragos

**Comment by irineos1995** [comment]
when is a new version going to be released to fix all the problems in the master branch?

**Comment by dragosct10** [comment]
Hi! Please tell us which problems did you have, because we will help you? For example, this problem with the autocomplete it's not from our part. We have to wait until vue-material framework will make an update. 

Regards, 
Dragos
