### ISSUE TITLE
 modal and sweetalert2 cannot work together

### ISSUE THREAD

**Issue by Thyiad** [creativetimofficial/ct-vue-material-dashboard-pro#72]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Use modal and sweetalert2 together

# Current Behavior

modal and sweetalert2 cannot work together

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. use modal
2. in js, use swal.fire open confirm, close confirm window
3. modal and confirm both closed

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: 
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by Thyiad** [comment]
![image](https://user-images.githubusercontent.com/3324812/56078987-c1820980-5e20-11e9-85bf-51a47e02dc58.png)
![image](https://user-images.githubusercontent.com/3324812/56078992-d8286080-5e20-11e9-9436-c44712f3f551.png)
the confirm is a wrapper of swal.fire

**Comment by dragosct10** [comment]
Hi, @Thyiad! They don't work together because the modal has an outside click directive so when the sweet alert its opening and you click on the sweet alert then also the modal it's closing. To fix it you must remove that outside click directive from the modal. 

Regards,
Dragos

**Comment by Thyiad** [comment]
@dragosct10 It works, thank you !
