### ISSUE TITLE
Import Components from UI Kit Pro

### ISSUE THREAD

**Issue by gaspo53** [creativetimofficial/ct-vue-material-dashboard-pro#73]
Hi! Is there any way to import a component from UI Kit Pro into Dashboard Pro? I've tried RotatingCards but with no luck, it breaks everywhere. That's the main reason why I've purchased the bundle.

Thanks

**Comment by dragosct10** [comment]
Hi, @gaspo53! Thank you for using our products. Yes, you can do this, but you have to take the component from the UI Kit PRO with also the SCSS together and put it in the Dashboard PRO components and then it will work. 

Regards, 
Dragos

**Comment by gaspo53** [comment]
Hi! Alright, thanks.
