### ISSUE TITLE
SideBarItem prefix as prop

### ISSUE THREAD

**Issue by Mr-Markus** [creativetimofficial/ct-vue-material-dashboard-pro#74]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

SideBarItem component should provide a prop for prefix. If it is set then the value should be displayed, otherwise inital characters can be used. It would also be greate if you are able to set a bool prop like "showPrefix" to control visibility

# Current Behavior

Currently there is no possibility to set the prefix in the sidebar item component. It is computed by initial characters of the name

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a sidebar
2. Create sidebar items
3. Open Sidebar menu with subitems

## Context

* Device: All
* Operating System: All
* Browser and Version: All

**Comment by dragosct10** [comment]
Hi, @Mr-Markus! Thank you for using our products. Please, can you be more specific about what you propose, because I didn't understand really good? 

Regards, 
Dragos

**Comment by Mr-Markus** [comment]
Hi @dragosct10,

I mean following:

![image](https://user-images.githubusercontent.com/38456692/56191974-aafccd80-602d-11e9-98b0-36c50afd6b23.png)

At the moment it is not possible to set it via prop from outside. This would be very helpful and a good enhancement to the template.

Thanks,
Markus

**Comment by dragosct10** [comment]
Hi! Ok, now I understand what you mean and thank you for this, we will take it into consideration. Regards, Dragos
