### ISSUE TITLE
VueMaterial.io is Dead and Issues

### ISSUE THREAD

**Issue by chrisjenx** [creativetimofficial/ct-vue-material-dashboard-pro#75]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

This template is not usable with the latest versions of VueJS 2.6+ as VueMaterial.io has multiple issues with it.
I can't even use `:to` or any other passthrough properties with the `<md` components.

You should really deprecate these templates based off the VueMaterial.io Components unless you are going to fork the project and fix the 150+ reported bugs.

**Comment by dragosct10** [comment]
Hi, @chrisjenx! Thank you for using our products. Yes, we are also disappointed about this but we've spoken with the guy who made the framework and he told us that now it's working on a new version of Vue material with fixed issues, so we will wait and then we will also update our products.  

Regards, 
Dragos

**Comment by chrisjenx** [comment]
@dragosct10 OK cool, I think moving this fully over to Vuetify would benefit us all, as that has a full time dev now due to its backing. Thanks!

**Comment by luismaldonadov** [comment]
Move to vuetify!
