### ISSUE TITLE
Some dashboard components styles not RTL friendly

### ISSUE THREAD

**Issue by eybarta** [creativetimofficial/ct-vue-material-dashboard-pro#76]
![ss-vmp](https://user-images.githubusercontent.com/12781988/58249257-0590f400-7d67-11e9-9f38-885ef7c8f48a.jpg)

As you can see the dot & bar graphs gets cut off when using
the RTL feature.. please update the components to look as expected
when used in RTL.

thx for all your work and support.

**Comment by dragosct10** [comment]
Hi, @eybarta! Thank you for using our products. Thank you for your feedback. You can put `text-align: right` on those elements. 

Regards, 
Dragos
