### ISSUE TITLE
Progress bar prepended styles bug

### ISSUE THREAD

**Issue by egorzot** [creativetimofficial/ct-vue-material-dashboard-pro#77]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I'm using progress bar like described in [docs](https://vuematerial.io/components/progress-bar/). 
In /src/assets/scss/md/_progress.scss there are some classes that prepend to use with progress bars. 

# Current Behavior
I try to use md-success class with md-progress-bar element.
Сlass "default-theme" automatically added to class attribute so progress bar becomes bicolour.

# Failure Information (for bugs)

## Steps to Reproduce

<md-progress-bar class="md-success" md-mode="indeterminate"></md-progress-bar>

## Context
* version 1.1.0 of vue-material-dashboard
* Desktop:
* Ubuntu 16.04:
* Chromium 73.0.3683.86:

**Comment by dragosct10** [comment]
Hi, @egorzot! Thank you for using our products. Please, can you give us a link to your project for this issue to see how we can fix it? 

Regards,
Dragos

**Comment by egorzot** [comment]
Hi @dragosct10!
I can’t but I can send you code example or create private repo with bug reprodusing. What do you prefer ?

**Comment by dragosct10** [comment]
Hi! Sorry for the late response. Yes, please sending us a code example would be great. 

Regards, 
Dragos
