### ISSUE TITLE
Incompatible units px and rem.

### ISSUE THREAD

**Issue by amorZhu** [creativetimofficial/ct-vue-material-dashboard-pro#78]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

` npm run dev` success.

# Current Behavior

I created a new laravel project.
I copied the files to the laravel sass directory.
I modified the package.json file.
![image](https://user-images.githubusercontent.com/17883773/58459154-4c169200-815d-11e9-9454-6a84228c61d1.png)
Execute the npm install && npm run dev command

# Failure Information (for bugs)

`npm run dev` info:
![image](https://user-images.githubusercontent.com/17883773/58458787-9c412480-815c-11e9-952e-a72bdcdee4d9.png)
![image](https://user-images.githubusercontent.com/17883773/58458924-de6a6600-815c-11e9-86c3-cb34b3a156a2.png)

## Context

* Device: Laravel Framework 5.8.18
* Operating System: Manjaro Linux
* Browser and Version: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by dragosct10** [comment]
Hi, @amorZhu! Thank you for using our products. Please, try to use the vuematerial version 1.0.0-beta-2, because beta 11 it's newly released and we have to make an update also in our product. Please tell us if everything working fine after this.

Regards,
Dragos
