### ISSUE TITLE
[Bug] After redirect value of scroll top stays the same.

### ISSUE THREAD

**Issue by Jakuboslav** [creativetimofficial/ct-vue-material-dashboard-pro#79]
### Version
1.2.0
### Reproduction link
https://this.is.not.needed.com
### Steps to reproduce
1. In your demo go to Regular Forms.
2. Scroll down as much as possible
3. WITHOUT SCROLLING Go to Dashboard
4. You see? We are not on the top of the page
### What is expected?
It is expected to return to the top of the page, when you change a page
### What is actually happening?
Position of viewport is stuck on the place where it was left.

---
### Solution
When you are redirected to another page, return top the top of the page.
### Additional comments
It is extremly annoying, when you have long form, submit it, and them you have to scroll up to get back. It is very disorienting and I see no point in this behaviour. When you are redirected you should see the top of the page right? Let me know if you consider it as a bug, or there is some kind of solution / walkaround.

**Comment by dragosct10** [comment]
Hi, @Jakuboslav! Thank you for using our products. Please take the latest version, this issue it's fixed there. 

Regards, 
Dragos

**Comment by Jakuboslav** [comment]
Hi @dragosct10, I am still experiencing this issue with 1.3.1.
It seems like scrollBehaviour, doesn't work as expected. 
I would like to know how to set up scrollBehaviour to make it work in Material Dashboard.

Btw, i can see the issue still in you demo too.
Can you take a look at it, please?

**Comment by dragosct10** [comment]
Hi, @Jakuboslav! I just want to show that on our side everything it's working fine. Please see the video attached. 

https://www.dropbox.com/s/22k8c0ocz4ucsqs/vuemdpro.mov?dl=0

Regards, 
Dragos
