### ISSUE TITLE
notifications timeout property doesn't work

### ISSUE THREAD

**Issue by irineos1995** [creativetimofficial/ct-vue-material-dashboard-pro#81]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
setting the property timeout like this:
```
this.$notify(
        {
          timeout: 99999999999999999999999999999999,
          message: 'Welcome to <b>Material Dashboard</b> - a beautiful freebie for every web developer.',
          icon: 'add_alert',
          horizontalAlign: horizontalAlign,
          verticalAlign: verticalAlign,
          type: 'warning',
        })
    }
```

should close the notification within 99999999999999999999999999999999 ms

# Current Behavior
auto closes the notification within 2.5 seconds which is the default value

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Laptop
* Operating System: Windows Intel
* Browser and Version: Google Chrome latest version

**Comment by irineos1995** [comment]
...

**Comment by dragosct10** [comment]
Hi, @irineos1995! Thank you for using our products. Sorry for the late response. To modify the seconds please go in src/components/NotificationPlugin/Notification.vue and there you have a prop timeout and please change there the time for the moment. We will fix this in the next update. 

Regards, 
Dragos

**Comment by irineos1995** [comment]
@dragosct10  Thank you. Will do that!
