### ISSUE TITLE
this.$notify Second Arg Obj

### ISSUE THREAD

**Issue by ahmadshahrour951** [creativetimofficial/ct-vue-material-dashboard-pro#82]
Hey at [the demo site](https://demos.creative-tim.com/vue-material-dashboard-pro/#/components/notifications). You mention looking at the documentation on the bootstrap plugin for further information on notifications. Their [docs](http://bootstrap-notify.remabledesigns.com/) say that one can pass another object to further configure the notification as such:

<img width="954" alt="Screen Shot 2019-07-03 at 12 27 16 PM" src="https://user-images.githubusercontent.com/33921028/60576307-36187480-9d8e-11e9-8621-adf52b3cfddb.png">

When I do pass the second object, nothing really happens.. could you help me out with this?.. In the `web/src/components/NotificationPlugin/Notification.vue` I see that it's not being passed as props...

**Comment by mrbio** [comment]
Hi.
I see no problems passing a single object to initialize a notification since it's design like that in Notifications.vue
