### ISSUE TITLE
New download fails to start with npm run dev

### ISSUE THREAD

**Issue by jaibhatia** [creativetimofficial/ct-vue-material-dashboard-pro#83]
# Prerequisites

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed
- [Yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
After downloading the 1.3.0 zip and extracting the file, running 
npm install
npm run dev
The dev version of the server should start

# Current Behavior

Getting error and dev server does not start due to compile issue

# Failure Information (for bugs)

 ERROR  Failed to compile with 1 errors                                                                                                              7:50:45 PM
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'D:\code\project\vue-material-dashboard-pro-v1.3.0\node_modules\eslint\lib\api.js/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.module.exports (D:\code\project\vue-material-dashboard-pro-v1.3.0\node_modules\eslint-loader\index.js:170:23)

## Steps to Reproduce
Download latest version
Extract it on windows
Run npm install
Run npm run dev

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Dev laptop
* Operating System: Windows 10
* Browser and Version: Chrome any

**Comment by UcheEke** [comment]
I had a similar issue today, different setup - Linux 64bit (Ubuntu 19.04):

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module  '.../vue-material-dashboard-pro-v1.3.0/node_modules/eslint/lib/api.js/package.json'"

I had copied the unzipped contents over to another directory when I first got the error earlier on today, so I ran the same steps as jaibhatia and got the message above. Ditto for Vue Material Kit Pro:

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module '.../vue-material-kit-pro-v1.1.0/node_modules/eslint/lib/api.js/package.json'

As an aside, I had played around with the same Material Kit download only a few days ago without this issue.

**Comment by dragosct10** [comment]
Hi guys! Thank you for using our product. Please check the version of the node and the npm, and please be sure to have the latest versions. 

Regards, 
Dragos

**Comment by jaibhatia** [comment]
Hi I have upgraded to the latest versions -
npm version 6.10.0
node version v12.6.0

I deleted node_modules, package-lock.json and did a reinstall. I am still facing the same issue.

Could you please give us a working package-lock.json file to see which versions need to be installed?

**Comment by dragosct10** [comment]
Hi! Of course, I will give my `package-lock.json`. Please take the file attached: 


[package-lock.json.zip](https://github.com/creativetimofficial/ct-vue-material-dashboard-pro/files/3358764/package-lock.json.zip)

Regards, 
Dragos

**Comment by jaibhatia** [comment]
Ok here is the solution -

This is a vue-cli bug that has just been fixed in version 3.9.1. The solution there works.

https://github.com/vuejs/vue-cli/issues/4231

On an existing project:

1) Delete node_modules
2) Delete package-lock.json
3) Edit package.json to require     "@vue/cli-plugin-eslint": "^3.9.1" in the devDependencies
4) clear cache - npm cache clean -f
5) npm install
6) npm run dev
- Worked for me.

Thanks!

**Comment by dragosct10** [comment]
I thought that was a bug from them and it's very nice of you to tell us the steps for fixing it. 

Regards, 
Dragos
