### ISSUE TITLE
Scrollbar is buggy when class ".menu-on-left" is applied

### ISSUE THREAD

**Issue by ker-nicolaib** [creativetimofficial/ct-vue-material-dashboard-pro#84]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

* Device: PC
* Operating System: Windows 10
* Browser and Version: Google Chrome Version 75.0.3770.100 (64-bit)

@dragosct10 
![Scrollbar](https://user-images.githubusercontent.com/52697003/60873623-f8f12e00-a236-11e9-9e95-ba28aa8a3337.gif)

**Comment by ker-nicolaib** [comment]
![menu_on_left](https://user-images.githubusercontent.com/52697003/60873936-7d43b100-a237-11e9-9c48-24f1e0a9afcd.PNG)

**Comment by dragosct10** [comment]
Hi, @ker-nicolaib! Sorry for the late response. We will do a quick update for this today. 

Regards, 
Dragos

**Comment by dragosct10** [comment]
You can download now the new update. I will close this.

Regards, 
Dragos
