### ISSUE TITLE
Reactivity inside <md-table-toolbar> fails.

### ISSUE THREAD

**Issue by mrbio** [creativetimofficial/ct-vue-material-dashboard-pro#87]
Hi!
I'm using vue material dashboard pro 1.3.0 and have an issue with dynamically populating "md-select" that's located inside "md-table-toolbar".
I have the following "md-select": 
`<md-select v-model="transaction_type_filter" name="trTypes">
  <md-option
  v-for="(index,trTypeName) in supportedTransactions"
  :key="index"
  :label="trTypeName"
  :value="trTypeName">
    {{trTypeName}}
  </md-option>
</md-select>`
The "supportedTransactions" is defined in data() section and being set in axios request.
But unfortunately template is not populated with new data when "md-select" component is located inside "md-table-toolbar".
Once I move it outside of "md-table-toolbar" everything work just fine.
I was unable to found an exact origin of this bug but I guess it's something inside "md-toolbar" or "md-table-toolbar".

**Comment by dragosct10** [comment]
Hi! Please use the app for creating the issue. We will close this. 

Regards, 
Dragos
