### ISSUE TITLE
[Bug] [SERIOUS BUG] TypeError: Cannot read property 'to' of undefined

### ISSUE THREAD

**Issue by irineos1995** [creativetimofficial/ct-vue-material-dashboard-pro#88]
### Version
1.2.0
### Operating System
Mac OS
### Device
MacBook Pro
### Browser & Version
Google Chrome Version 76.0.3809.100
### Steps to reproduce
It looks like https://nodejs.org/en/blog/ updated and now the dashboard sidebar is having problems.
I cannot locate the exact problem. Can you please advise me on how to fix it?
### What is expected?
Work as before. I changed nothing apart from rebuilding my container and now node is on version: Node v10.16.1 (LTS)
### What is actually happening?
breaks with the error I put in the title

---

**Comment by irineos1995** [comment]
found the solution to the problem:
https://github.com/vuejs/vue-router/releases
the problem was with Vue-router. The working version is v3.0.7.
Since their new updates, the introduction of new bugs have been made!

**Comment by dragosct10** [comment]
Hi, @irineos1995! Thank you for using our products. Please, update the product to the latest version, because there you will have all the latest updates for the dependencies. 

Regards, 
Dragos
