### ISSUE TITLE
[Bug] error: Parsing error: Unexpected token import

### ISSUE THREAD

**Issue by adubkov** [creativetimofficial/ct-vue-material-dashboard-pro#89]
### Version
1.3.1
### Reproduction link
http://localhost
### Operating System
doesn't matter
### Device
doesn't matter
### Browser & Version
doesn't matter
### Steps to reproduce
yarn build
### What is expected?
it should build without errors
### What is actually happening?
```
Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token import at src/components/WorldMap/AsyncWorldMap.vue:11:13:
   9 |
  10 | const WorldMap = () => ({
> 11 |   component: import("./WorldMap.vue"),
     |             ^
  12 |
  13 |   delay: 200
  14 | });


1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token import at src/components/WorldMap/WorldMap.vue:45:10:
  43 |   async mounted() {
  44 |     window.$ = window.jQuery = $;
> 45 |     await import("jvectormap-next");
     |          ^
  46 |     await import("./world_map");
  47 |     this.initVectorMap();
  48 |   }


1 error found.
```
---

**Comment by dragosct10** [comment]
Hi, @adubkov! Thank you for using our products. Very strange error because I just tested and everything it's fine in our side with the build product command, but please be sure that you have installed the latest NPM and NODEJS versions and after that please remove `node_modules` + `package-lock.json`  and run again `npm install` command. 

Regards,
Dragos

**Comment by adubkov** [comment]
Hi @dragosct10,
Thanks for reply. I actually tried uninstall npm+node+yarn+node_modules and upgrade everything to latest, but i'm still getting same error.

Maybe this will be helpful:
```
$ npm  version
{
  'vue-material-dashboard-pro': '1.3.1',
  npm: '6.10.3',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '4',
  nghttp2: '1.39.2',
  node: '12.9.1',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.31.0',
  v8: '7.6.303.29-node.15',
  zlib: '1.2.11'
}
```

**Comment by adubkov** [comment]
Settings this solved my problem:
```bash
$ cat .eslintrc.js
module.exports = {
  extends: [
    "plugin:vue/essential"
  ],
  parserOptions: {
    "ecmaVersion": 2017
  }
};
```

**Comment by dragosct10** [comment]
Hi! Thank you for the solution.  

Regards, 
Dragos
