### ISSUE TITLE
Printable version

### ISSUE THREAD

**Issue by LuanFreitas** [creativetimofficial/ct-vue-material-dashboard-pro#9]
Is there a way (or plugin) to print the dashboard screen like a report? Excluding icons and other images. Thanks.

**Comment by dragosct10** [comment]
Hi, @LuanFreitas! Thank you for using our products. Did you try to print the screen with the browser print function? 

Regards, 
Dragos

**Comment by LuanFreitas** [comment]
I've already found an alternative, thank you!

**Comment by LaravDev** [comment]
@LuanFreitas can you share what alternative you found? you mean like generating PDF reports? thanks in advance
