### ISSUE TITLE
[Feature Request] Support Google Chrome version 49

### ISSUE THREAD

**Issue by algakzru** [creativetimofficial/ct-vue-material-dashboard-pro#92]
### What is your enhancement?
Vue Material Dashboard PRO works very well on the new version of Google Chrome, but unfortunately it doesn't work on Google Chrome version 49.
All computers in our company by default have Google Chrome version 49 preinstalled and nobody will change the default version of the browser just because our website doesn't support it.
We like Vue Material Dashboard PRO very much and would love to use it in our website, but we can't, because of the browser version incompatibility.
So my feature request - please make it support old browsers too, otherwise some of your customers (like me) just wouldn't be able to use it

**Comment by dragosct10** [comment]
Hi, @algakzru! Thank you for using our products. Please, see this link https://forum.vuejs.org/t/browser-compatibility-vue-cli-3-code-is-not-being-transpiled/41694. It seems that the vue cli 3 is not compatible by default with the older chrome versions. 

Regards,
Dragos
