### ISSUE TITLE
[Feature Request] Provision to configure webpack

### ISSUE THREAD

**Issue by carangan-zoom2u** [creativetimofficial/ct-vue-material-dashboard-pro#93]
### What is your enhancement?
Hi. I just want to ask if there is a way to change the webpack configuration of the theme. I'd like to know where and how to do it. I've tried using vue.config.js but it seems to be not working at the moment. Thank you!

**Comment by dragosct10** [comment]
Hi, @carangan-zoom2u! Thank you for using our products. Please read this https://cli.vuejs.org/guide/webpack.html and here you will find how to work with the webpack. 

Regards, 
Dragos

**Comment by carangan-zoom2u** [comment]
Hi. This is a followup question. In the Sidebar.vue component, where is the method responsible for minimizing/expanding the sidebar when hovering on it? I cannot seem to find it. Thank you!

**Comment by dragosct10** [comment]
Hi, @carangan-zoom2u! The function that minimizes the sidebar is in `src/components/SidebarPlugin/index.js` named `toggleMinimize()`. 

Regards, 
Dragos
