### ISSUE TITLE
[Bug] Login card does not work with return (enter) event

### ISSUE THREAD

**Issue by fecilak** [creativetimofficial/ct-vue-material-dashboard-pro#95]
### Version
1.3.1
### Reproduction link
https://demos.creative-tim.com/vue-material-dashboard-pro/documentation/component-docs/cards.html#login-card
### Operating System
not relevant (Windows and Linux)
### Device
Laptop
### Browser & Version
Chrome, Opera, Firefox (all of them latest)
### Steps to reproduce
Following the documentation, we have implemented login dialog as per demos -> Cards -> Login card.
Login button is registered with the event "v-on:keyup.enter". 
However, login page does not take any action when hitting return/enter. The event is not fired.
### What is expected?
It is expected to submit the form (login dialog) in two ways - clicking on the button (which works) and by hitting enter/return after entering password).
### What is actually happening?
The login process work correctly by clicking on the button. It does not take action when enter/return is pressed.

---

**Comment by dragosct10** [comment]
Hi, @fecilak! Buttons don't have keyup event on them. Please see here the vuejs [docs](https://vuejs.org/v2/guide/events.html) or https://stackoverflow.com/questions/46955147/enter-with-keyup-event-not-working-in-vue. Hope this will be helpful for you! 

Regards, 
Dragos
