### ISSUE TITLE
[Bug] Login card fields autocompletition field overlaying issue

### ISSUE THREAD

**Issue by fecilak** [creativetimofficial/ct-vue-material-dashboard-pro#96]
### Version
1.3.1
### Reproduction link
https://demos.creative-tim.com/vue-material-dashboard-pro/documentation/component-docs/cards.html#login-card
### Operating System
not relevant (Windows and Linux)
### Device
Laptop
### Browser & Version
Chrome, Opera, Firefox (all of them latest)
### Steps to reproduce
1. Login card dialog is implemented as per documentation -> Cards -> Login card
2. When login&password is automatically stored and browser is filling the fields automatically, field descriptions (e.g. First Name, Email, Password) which are normally animated and moving above the field when clicking into the field, are not moving and stays overlayed on top of the automatically prefilled login/password fields.
### What is expected?
Field descriptions should not be overlaying the field when it is automatically filled by browser from saved passwords.
### What is actually happening?
When browser automatically fills the fields (e.g. login &passwords), the fields stays overlayed with the field descriptions (e.g. First Name, Email, Password) which are overlaying the field input.

---
### Solution
Have no idea - it should trigger somewhere automatically when the browser is prefilling the fields...

**Comment by dragosct10** [comment]
Hi, @fecilak! For this issue, unfortunately, we have to wait until the vuematerial will fix this because the issue is not from us, the issue is from the vuematerial component and we don't have control over it. We will write to them about this issue and we hope to deal with it as soon as possible.

Thank you for your understanding! 

Regards, 
Dragos

**Comment by fecilak** [comment]
Is there any update on this?

**Comment by dragosct10** [comment]
Hi! We are sorry for the late response, but anyway the issue is not fixed yet. 

Regards,
Dragos

**Comment by fecilak** [comment]
after 2 years there is no update on this?

**Comment by dragosict** [comment]
@fecilak Is not fixed because vue-material still is not updated :(. We are searching for a team who will bring to life the framework.
