### ISSUE TITLE
Bug with \node_modules\open\index.js

### ISSUE THREAD

**Issue by elluminati-dev** [creativetimofficial/ct-vue-material-dashboard-pro#97]
It gives error during build regarding the "path" variable against async as attached with the screenshot. 

**Note : All libraries were successfully build using npm** 
![picturemessage_qglmecw0 5p1](https://user-images.githubusercontent.com/57990115/69512845-a4431b00-0f6b-11ea-881d-f99baa661550.png)

**Comment by dragosct10** [comment]
Hi, @elluminati-dev! Thank you for using our products. Please be sure that you have the latest npm and nodejs installed and then try again. 

Regards,
Dragos

**Comment by elluminati-dev** [comment]
Hello @dragosct10 We did, Could you provide us with the npm & node version of the template ?

**Comment by dragosct10** [comment]
Hi! We use node v12.13.0 and npm v6.12.1. I have a question if you try to build the product fresh without any change, will work? 

Regards, 
Dragos
