### ISSUE TITLE
Sidebar Plugin - Expand Only One Issue

### ISSUE THREAD

**Issue by varinderunoia** [creativetimofficial/ct-vue-material-dashboard-pro#98]
Hi,

We are currently using Vue Material Dashboard Pro. There is an issue with the Sidebar component. The sidebar component doesn't work as expected. It should expand only one sidebar item but it is allowing the user to expand as many sidebar items as they are clicked. We should have access to expand only one sidebar item. So, kindly look into this matter and fix this. We have attached a screenshot for it.
![sidebarissue](https://user-images.githubusercontent.com/51073828/69782366-cf7d7280-11d6-11ea-86a5-d0db9728de87.png)

**Comment by dragosct10** [comment]
Hi, @varinderunoia! Thank you for using our products. This is already fixed and we will do an update tomorrow with this. 

Thank you for your understanding! 

Regards, 
Dragos
