### ISSUE TITLE
Wizard - Mobile vue

### ISSUE THREAD

**Issue by abn50167** [creativetimofficial/ct-vue-material-dashboard-pro#99]
Hello,

I found a bug when showing wizard with a mobile phone.
Steps bar not rendered correctely.

![image](https://user-images.githubusercontent.com/15875145/70044490-c3bcf200-15c2-11ea-8534-0c95705804e5.png)

**Comment by dragosct10** [comment]
Hi, @abn50167! Thank you for using our products. We will check this issue and we will come with a solution. 

Regards,
Dragos

**Comment by dragosct10** [comment]
Hi, @abn50167! We've tested this on a real phone and the bug is not present there. Please check it on a real phone to see it. 

Regards, 
Dragos
